import { db } from "./config";
import { Category, Color, Photo, Product, Variant, Volt } from "./schema";

const ALL_COLORS = [
  { id: 1, color: "colors.black" },
  { id: 2, color: "colors.white" },
  { id: 3, color: "colors.grafite" },
  { id: 4, color: "colors.blueFire" },
  { id: 5, color: "colors.redFire" },
  { id: 6, color: "colors.hiphop" },
  { id: 7, color: "colors.pinkCamouflage" },
  { id: 8, color: "colors.purple" },
  { id: 9, color: "colors.blueCamouflage" },
  { id: 10, color: "colors.rosePink" },
  { id: 11, color: "colors.inox" },
  { id: 12, color: "Inox" },
  { id: 13, color: "colors.RedAndBlack" },
  { id: 14, color: "colors.BlueAndWhite" },
  { id: 15, color: "colors.GrayAndBronze" },
  { id: 16, color: "colors.golden" },
  { id: 17, color: "colors.blankAndWhite" },
  { id: 18, color: "colors.blackAndGray" },
];

const ALL_CATEGORIES = [
  {
    id: "tvs",
    name: "tvs.name",
    description: "tvs.description",
    shortDescription: "tvs.shortDescription",
  },
  {
    id: "scooters",
    name: "scooters.name",
    description: "scooters.description",
    shortDescription: "scooters.shortDescription",
  },
  {
    id: "aires",
    name: "aires.name",
    description: "aires.description",
    shortDescription: "aires.shortDescription",
  },
  {
    id: "hoverboards",
    name: "hoverboards.name",
    description: "hoverboards.description",
    shortDescription: "hoverboards.shortDescription",
  },
  {
    id: "airfryer",
    name: "airfryer.name",
    description: "airfryer.description",
    shortDescription: "airfryer.shortDescription",
  },
  {
    id: "mixteras",
    name: "mixteras.name",
    description: "mixteras.description",
    shortDescription: "mixteras.shortDescription",
  },
  {
    id: "cocinas",
    name: "cocinas.name",
    description: "cocinas.description",
    shortDescription: "cocinas.shortDescription",
  },
  {
    id: "hervidoras",
    name: "hervidoras.name",
    description: "hervidoras.description",
    shortDescription: "hervidoras.shortDescription",
  },
  {
    id: "cafeteras",
    name: "cafeteras.name",
    description: "cafeteras.description",
    shortDescription: "cafeteras.shortDescription",
  },
  {
    id: "planchas",
    name: "planchas.name",
    description: "planchas.description",
    shortDescription: "planchas.shortDescription",
  },
  {
    id: "licuadoras",
    name: "licuadoras.name",
    description: "licuadoras.description",
    shortDescription: "licuadoras.shortDescription",
  },
  {
    id: "beauty",
    name: "beauty.name",
    description: "beauty.description",
    shortDescription: "beauty.shortDescription",
  },
  {
    id: "batidoras",
    name: "batidoras.name",
    description: "batidoras.description",
    shortDescription: "batidoras.shortDescription",
  },
  {
    id: "arroceras",
    name: "arroceras.name",
    description: "arroceras.description",
    shortDescription: "arroceras.shortDescription",
  },
  {
    id: "bebederos",
    name: "bebederos.name",
    description: "bebederos.description",
    shortDescription: "bebederos.shortDescription",
  },
];

const ALL_PRODUCTS = [
  {
    id: "IN3200TV",
    category_id: "tvs",
    name: "tvs.children.1.name",
    review: "tvs.children.1.info.review",

    specs: "tvs.children.1.info.specs",
  },
  {
    id: "IN4300TV",
    category_id: "tvs",
    name: "tvs.children.2.name",
    review: "tvs.children.2.info.review",

    specs: "tvs.children.2.info.specs",
  },
  {
    id: "IN5000TV",
    category_id: "tvs",
    name: "tvs.children.3.name",
    review: "tvs.children.3.info.review",

    specs: "tvs.children.3.info.specs",
  },
  {
    id: "IN5500TV",
    category_id: "tvs",
    name: "tvs.children.4.name",
    review: "tvs.children.4.info.review",

    specs: "tvs.children.4.info.specs",
  },
  {
    id: "IN6500TV",
    category_id: "tvs",
    name: "tvs.children.5.name",
    review: "tvs.children.5.info.review",

    specs: "tvs.children.5.info.specs",
  },
  {
    id: "IN7500TV",
    category_id: "tvs",
    name: "tvs.children.6.name",
    review: "tvs.children.6.info.review",

    specs: "tvs.children.6.info.specs",
  },
  {
    id: "IN8500TV",
    category_id: "tvs",
    name: "tvs.children.7.name",
    review: "tvs.children.7.info.review",

    specs: "tvs.children.7.info.specs",
  },
  {
    id: "8.5",
    category_id: "scooters",
    name: "scooters.children.85.name",
    review: "scooters.children.85.info.review",

    specs: "scooters.children.85.info.specs",
  },
  {
    id: "10.5pro",
    category_id: "scooters",
    name: "scooters.children.10pro.name",
    review: "scooters.children.10pro.info.review",

    specs: "scooters.children.10pro.info.specs",
  },
  {
    id: "cross",
    category_id: "scooters",
    name: "scooters.children.cross.name",
    review: "scooters.children.cross.info.review",

    specs: "scooters.children.cross.info.specs",
  },
  {
    id: "crosspro",
    category_id: "scooters",
    name: "scooters.children.crosspro.name",
    review: "scooters.children.crosspro.info.review",

    specs: "scooters.children.crosspro.info.specs",
  },
  {
    id: "itb-12000iv",
    category_id: "aires",
    name: "aires.children.1.name",
    review: "aires.children.1.info.review",

    specs: "aires.children.1.info.specs",
  },
  {
    id: "itp-12000iv",
    category_id: "aires",
    name: "aires.children.2.name",
    review: "aires.children.2.info.review",

    specs: "aires.children.2.info.specs",
  },
  {
    id: "itb-12000of",
    category_id: "aires",
    name: "aires.children.3.name",
    review: "aires.children.3.info.review",

    specs: "aires.children.3.info.specs",
  },
  {
    id: "itp-12000of",
    category_id: "aires",
    name: "aires.children.4.name",
    review: "aires.children.4.info.review",

    specs: "aires.children.4.info.specs",
  },
  {
    id: "itb-18000iv",
    category_id: "aires",
    name: "aires.children.5.name",
    review: "aires.children.5.info.review",

    specs: "aires.children.5.info.specs",
  },
  {
    id: "itb-24000iv",
    category_id: "aires",
    name: "aires.children.6.name",
    review: "aires.children.6.info.review",

    specs: "aires.children.6.info.specs",
  },
  {
    id: "hoverboards1",
    category_id: "hoverboards",
    name: "hoverboards.children.hoverboards1.name",
    review: "hoverboards.children.hoverboards1.info.review",

    specs: "hoverboards.children.hoverboards1.info.specs",
  },
  {
    id: "hoverboards2",
    category_id: "hoverboards",
    name: "hoverboards.children.hoverboards2.name",
    review: "hoverboards.children.hoverboards2.info.review",

    specs: "hoverboards.children.hoverboards2.info.specs",
  },
  {
    id: "hoverboards3",
    category_id: "hoverboards",
    name: "hoverboards.children.hoverboards3.name",
    review: "hoverboards.children.hoverboards3.info.review",

    specs: "hoverboards.children.hoverboards3.info.specs",
  },
  {
    id: "hoverboards4",
    category_id: "hoverboards",
    name: "hoverboards.children.hoverboards4.name",
    review: "hoverboards.children.hoverboards4.info.review",

    specs: "hoverboards.children.hoverboards4.info.specs",
  },
  {
    id: "hoverboards5",
    category_id: "hoverboards",
    name: "hoverboards.children.hoverboards5.name",
    review: "hoverboards.children.hoverboards5.info.review",

    specs: "hoverboards.children.hoverboards5.info.specs",
  },
  {
    id: "hoverboards6",
    category_id: "hoverboards",
    name: "hoverboards.children.hoverboards6.name",
    review: "hoverboards.children.hoverboards6.info.review",

    specs: "hoverboards.children.hoverboards6.info.specs",
  },
  {
    id: "hoverboards7",
    category_id: "hoverboards",
    name: "hoverboards.children.hoverboards7.name",
    review: "hoverboards.children.hoverboards7.info.review",

    specs: "hoverboards.children.hoverboards7.info.specs",
  },
  {
    id: "hoverboards8",
    category_id: "hoverboards",
    name: "hoverboards.children.hoverboards8.name",
    review: "hoverboards.children.hoverboards8.info.review",

    specs: "hoverboards.children.hoverboards8.info.specs",
  },
  {
    id: "hoverboards9",
    category_id: "hoverboards",
    name: "hoverboards.children.hoverboards9.name",
    review: "hoverboards.children.hoverboards9.info.review",

    specs: "hoverboards.children.hoverboards9.info.specs",
  },
  {
    id: "s10",
    category_id: "airfryer",
    name: "airfryer.children.s10.name",
    review: "airfryer.children.s10.info.review",

    specs: "airfryer.children.s10.info.specs",
  },
  {
    id: "s20",
    category_id: "airfryer",
    name: "airfryer.children.s20.name",
    review: "airfryer.children.s20.info.review",

    specs: "airfryer.children.s20.info.specs",
  },
  {
    id: "s30",
    category_id: "airfryer",
    name: "airfryer.children.s30.name",
    review: "airfryer.children.s30.info.review",

    specs: "airfryer.children.s30.info.specs",
  },
  {
    id: "s40",
    category_id: "airfryer",
    name: "airfryer.children.s40.name",
    review: "airfryer.children.s40.info.review",

    specs: "airfryer.children.s40.info.specs",
  },
  {
    id: "G10",
    category_id: "mixteras",
    name: "mixteras.children.G10.name",
    review: "mixteras.children.G10.info.review",

    specs: "mixteras.children.G10.info.specs",
  },
  {
    id: "G20",
    category_id: "mixteras",
    name: "mixteras.children.G20.name",
    review: "mixteras.children.G20.info.review",

    specs: "mixteras.children.G20.info.specs",
  },
  {
    id: "G30",
    category_id: "mixteras",
    name: "mixteras.children.G30.name",
    review: "mixteras.children.G30.info.review",

    specs: "mixteras.children.G30.info.specs",
  },
  {
    id: "G40",
    category_id: "mixteras",
    name: "mixteras.children.G40.name",
    review: "mixteras.children.G40.info.review",

    specs: "mixteras.children.G40.info.specs",
  },
  {
    id: "G50",
    category_id: "mixteras",
    name: "mixteras.children.G50.name",
    review: "mixteras.children.G50.info.review",

    specs: "mixteras.children.G50.info.specs",
  },
  {
    id: "C10",
    category_id: "cocinas",
    name: "cocinas.children.C10.name",
    review: "cocinas.children.C10.info.review",

    specs: "cocinas.children.C10.info.specs",
  },
  {
    id: "C20",
    category_id: "cocinas",
    name: "cocinas.children.C20.name",
    review: "cocinas.children.C20.info.review",

    specs: "cocinas.children.C20.info.specs",
  },
  {
    id: "C30",
    category_id: "cocinas",
    name: "cocinas.children.C30.name",
    review: "cocinas.children.C30.info.review",

    specs: "cocinas.children.C30.info.specs",
  },
  {
    id: "T10",
    category_id: "hervidoras",
    name: "hervidoras.children.T10.name",
    review: "hervidoras.children.T10.info.review",

    specs: "hervidoras.children.T10.info.specs",
  },
  {
    id: "T20",
    category_id: "hervidoras",
    name: "hervidoras.children.T20.name",
    review: "hervidoras.children.T20.info.review",

    specs: "hervidoras.children.T20.info.specs",
  },
  {
    id: "T30",
    category_id: "hervidoras",
    name: "hervidoras.children.T30.name",
    review: "hervidoras.children.T30.info.review",

    specs: "hervidoras.children.T30.info.specs",
  },
  {
    id: "E10",
    category_id: "cafeteras",
    name: "cafeteras.children.E10.name",
    review: "cafeteras.children.E10.info.review",

    specs: "cafeteras.children.E10.info.specs",
  },
  {
    id: "F10",
    category_id: "planchas",
    name: "planchas.children.F10.name",
    review: "planchas.children.F10.info.review",

    specs: "planchas.children.F10.info.specs",
  },
  {
    id: "F20",
    category_id: "planchas",
    name: "planchas.children.F20.name",
    review: "planchas.children.F20.info.review",

    specs: "planchas.children.F20.info.specs",
  },
  {
    id: "F30",
    category_id: "planchas",
    name: "planchas.children.F30.name",
    review: "planchas.children.F30.info.review",

    specs: "planchas.children.F30.info.specs",
  },
  {
    id: "F40",
    category_id: "planchas",
    name: "planchas.children.F40.name",
    review: "planchas.children.F40.info.review",

    specs: "planchas.children.F40.info.specs",
  },
  {
    id: "F50",
    category_id: "planchas",
    name: "planchas.children.F50.name",
    review: "planchas.children.F50.info.review",

    specs: "planchas.children.F50.info.specs",
  },
  {
    id: "L10",
    category_id: "licuadoras",
    name: "licuadoras.children.L10.name",
    review: "licuadoras.children.L10.info.review",
    included: "licuadoras.children.L10.info.included",
    specs: "licuadoras.children.L10.info.specs",
  },
  {
    id: "L20",
    category_id: "licuadoras",
    name: "licuadoras.children.L20.name",
    review: "licuadoras.children.L20.info.review",
    included: "licuadoras.children.L20.info.included",
    specs: "licuadoras.children.L20.info.specs",
  },
  {
    id: "L30",
    category_id: "licuadoras",
    name: "licuadoras.children.L30.name",
    review: "licuadoras.children.L30.info.review",
    included: "licuadoras.children.L30.info.included",
    specs: "licuadoras.children.L30.info.specs",
  },
  {
    id: "L40",
    category_id: "licuadoras",
    name: "licuadoras.children.L40.name",
    review: "licuadoras.children.L40.info.review",
    included: "licuadoras.children.L40.info.included",
    specs: "licuadoras.children.L40.info.specs",
  },
  {
    id: "603D",
    category_id: "beauty",
    name: "beauty.children.603D.name",
    review: "beauty.children.603D.info.review",

    specs: "beauty.children.603D.info.specs",
  },
  {
    id: "HB40",
    category_id: "beauty",
    name: "beauty.children.HB40.name",
    review: "beauty.children.HB40.info.review",

    specs: "beauty.children.HB40.info.specs",
  },
  {
    id: "HD008",
    category_id: "beauty",
    name: "beauty.children.HD008.name",
    review: "beauty.children.HD008.info.review",

    specs: "beauty.children.HD008.info.specs",
  },
  {
    id: "RFCD865",
    category_id: "beauty",
    name: "beauty.children.RFCD865.name",
    review: "beauty.children.RFCD865.info.review",

    specs: "beauty.children.RFCD865.info.specs",
  },
  {
    id: "B10",
    category_id: "batidoras",
    name: "batidoras.children.B10.name",
    review: "batidoras.children.B10.info.review",

    specs: "batidoras.children.B10.info.specs",
  },
  {
    id: "B20",
    category_id: "batidoras",
    name: "batidoras.children.B20.name",
    review: "batidoras.children.B20.info.review",

    specs: "batidoras.children.B20.info.specs",
  },
  {
    id: "B30",
    category_id: "batidoras",
    name: "batidoras.children.B30.name",
    review: "batidoras.children.B30.info.review",

    specs: "batidoras.children.B30.info.specs",
  },
  {
    id: "A10",
    category_id: "arroceras",
    name: "arroceras.children.A10.name",
    review: "arroceras.children.A10.info.review",
    included: "arroceras.children.A10.info.included",
    specs: "arroceras.children.A10.info.specs",
  },
  {
    id: "P10",
    category_id: "arroceras",
    name: "arroceras.children.P10.name",
    review: "arroceras.children.P10.info.review",

    specs: "arroceras.children.P10.info.specs",
  },
  {
    id: "W10",
    category_id: "bebederos",
    name: "bebederos.children.W10.name",
    review: "bebederos.children.W10.info.review",

    specs: "bebederos.children.W10.info.specs",
  },
];

const ALL_VARIANTS = [
  {
    id: 1,
    product_id: "IN3200TV",
    color_id: 1,
    volt_id: 1,
    catalog_id: 269,
  },
  {
    id: 2,
    product_id: "IN3200TV",
    color_id: 1,
    volt_id: 2,
    catalog_id: 269,
  },
  {
    id: 3,
    product_id: "IN3200TV",
    color_id: 1,
    volt_id: 3,
    catalog_id: 269,
  },
  {
    id: 4,
    product_id: "IN4300TV",
    color_id: 1,
    volt_id: 1,
    catalog_id: 270,
  },
  {
    id: 5,
    product_id: "IN4300TV",
    color_id: 1,
    volt_id: 2,
    catalog_id: 270,
  },
  {
    id: 6,
    product_id: "IN4300TV",
    color_id: 1,
    volt_id: 3,
    catalog_id: 270,
  },
  {
    id: 7,
    product_id: "IN5000TV",
    color_id: 1,
    volt_id: 1,
  },
  {
    id: 8,
    product_id: "IN5000TV",
    color_id: 1,
    volt_id: 2,
  },
  {
    id: 9,
    product_id: "IN5000TV",
    color_id: 1,
    volt_id: 3,
  },
  {
    id: 10,
    product_id: "IN5500TV",
    color_id: 1,
    volt_id: 1,
    catalog_id: 168,
  },
  {
    id: 11,
    product_id: "IN5500TV",
    color_id: 1,
    volt_id: 2,
    catalog_id: 168,
  },
  {
    id: 12,
    product_id: "IN5500TV",
    color_id: 1,
    volt_id: 3,
    catalog_id: 168,
  },
  {
    id: 13,
    product_id: "IN6500TV",
    color_id: 1,
    volt_id: 1,
    catalog_id: 159,
  },
  {
    id: 14,
    product_id: "IN6500TV",
    color_id: 1,
    volt_id: 2,
    catalog_id: 159,
  },
  {
    id: 15,
    product_id: "IN6500TV",
    color_id: 1,
    volt_id: 3,
    catalog_id: 159,
  },
  {
    id: 16,
    product_id: "IN7500TV",
    color_id: 1,
    volt_id: 1,
    catalog_id: 156,
  },
  {
    id: 17,
    product_id: "IN7500TV",
    color_id: 1,
    volt_id: 2,
    catalog_id: 156,
  },
  {
    id: 18,
    product_id: "IN7500TV",
    color_id: 1,
    volt_id: 3,
    catalog_id: 156,
  },
  {
    id: 19,
    product_id: "IN8500TV",
    color_id: 1,
    volt_id: 1,
    catalog_id: 167,
  },
  {
    id: 20,
    product_id: "IN8500TV",
    color_id: 1,
    volt_id: 2,
    catalog_id: 167,
  },
  {
    id: 21,
    product_id: "IN8500TV",
    color_id: 1,
    volt_id: 3,
    catalog_id: 167,
  },
  {
    id: 22,
    product_id: "8.5",
    color_id: 1,
    volt_id: 1,
    catalog_id: 253,
  },
  {
    id: 23,
    product_id: "8.5",
    color_id: 1,
    volt_id: 2,
    catalog_id: 253,
  },
  {
    id: 24,
    product_id: "8.5",
    color_id: 1,
    volt_id: 3,
    catalog_id: 253,
  },
  {
    id: 25,
    product_id: "8.5",
    color_id: 1,
    volt_id: 1,
    catalog_id: 252,
  },
  {
    id: 26,
    product_id: "8.5",
    color_id: 1,
    volt_id: 2,
    catalog_id: 252,
  },
  {
    id: 27,
    product_id: "8.5",
    color_id: 1,
    volt_id: 3,
    catalog_id: 252,
  },
  {
    id: 28,
    product_id: "10.5pro",
    color_id: 1,
    volt_id: 1,
    catalog_id: 254,
  },
  {
    id: 29,
    product_id: "10.5pro",
    color_id: 1,
    volt_id: 2,
    catalog_id: 254,
  },
  {
    id: 30,
    product_id: "10.5pro",
    color_id: 1,
    volt_id: 3,
    catalog_id: 254,
  },
  {
    id: 31,
    product_id: "cross",
    color_id: 1,
    volt_id: 1,
  },
  {
    id: 32,
    product_id: "cross",
    color_id: 1,
    volt_id: 2,
  },
  {
    id: 33,
    product_id: "cross",
    color_id: 1,
    volt_id: 3,
  },
  {
    id: 34,
    product_id: "crosspro",
    color_id: 1,
    volt_id: 1,
  },
  {
    id: 35,
    product_id: "crosspro",
    color_id: 1,
    volt_id: 2,
  },
  {
    id: 36,
    product_id: "crosspro",
    color_id: 1,
    volt_id: 3,
  },
  {
    id: 37,
    product_id: "itb-12000iv",
    color_id: 2,
    volt_id: 1,
    catalog_id: 81,
  },
  {
    id: 38,
    product_id: "itb-12000iv",
    color_id: 2,
    volt_id: 2,
    catalog_id: 81,
  },
  {
    id: 39,
    product_id: "itb-12000iv",
    color_id: 2,
    volt_id: 3,
    catalog_id: 81,
  },
  {
    id: 40,
    product_id: "itp-12000iv",
    color_id: 2,
    volt_id: 1,
    catalog_id: 71,
  },
  {
    id: 41,
    product_id: "itp-12000iv",
    color_id: 2,
    volt_id: 2,
    catalog_id: 71,
  },
  {
    id: 42,
    product_id: "itp-12000iv",
    color_id: 2,
    volt_id: 3,
    catalog_id: 71,
  },
  {
    id: 43,
    product_id: "itb-12000of",
    color_id: 2,
    volt_id: 1,
    catalog_id: 69,
  },
  {
    id: 44,
    product_id: "itb-12000of",
    color_id: 2,
    volt_id: 2,
    catalog_id: 69,
  },
  {
    id: 45,
    product_id: "itb-12000of",
    color_id: 2,
    volt_id: 3,
    catalog_id: 69,
  },
  {
    id: 46,
    product_id: "itp-12000of",
    color_id: 2,
    volt_id: 1,
    catalog_id: 68,
  },
  {
    id: 47,
    product_id: "itp-12000of",
    color_id: 2,
    volt_id: 2,
    catalog_id: 68,
  },
  {
    id: 48,
    product_id: "itp-12000of",
    color_id: 2,
    volt_id: 3,
    catalog_id: 68,
  },
  {
    id: 49,
    product_id: "itb-18000iv",
    color_id: 2,
    volt_id: 1,
    catalog_id: 80,
  },
  {
    id: 50,
    product_id: "itb-18000iv",
    color_id: 2,
    volt_id: 2,
    catalog_id: 80,
  },
  {
    id: 51,
    product_id: "itb-18000iv",
    color_id: 2,
    volt_id: 3,
    catalog_id: 80,
  },
  {
    id: 52,
    product_id: "itb-24000iv",
    color_id: 2,
    volt_id: 1,
    catalog_id: 82,
  },
  {
    id: 53,
    product_id: "itb-24000iv",
    color_id: 2,
    volt_id: 2,
    catalog_id: 82,
  },
  {
    id: 54,
    product_id: "itb-24000iv",
    color_id: 2,
    volt_id: 3,
    catalog_id: 82,
  },
  {
    id: 55,
    product_id: "hoverboards1",
    color_id: 1,
    volt_id: 1,
    catalog_id: 258,
  },
  {
    id: 56,
    product_id: "hoverboards1",
    color_id: 1,
    volt_id: 2,
    catalog_id: 258,
  },
  {
    id: 57,
    product_id: "hoverboards1",
    color_id: 1,
    volt_id: 3,
    catalog_id: 258,
  },
  {
    id: 58,
    product_id: "hoverboards2",
    color_id: 3,
    volt_id: 1,
    catalog_id: 332,
  },
  {
    id: 59,
    product_id: "hoverboards2",
    color_id: 3,
    volt_id: 2,
    catalog_id: 332,
  },
  {
    id: 60,
    product_id: "hoverboards2",
    color_id: 3,
    volt_id: 3,
    catalog_id: 332,
  },
  {
    id: 61,
    product_id: "hoverboards3",
    color_id: 4,
    volt_id: 1,
    catalog_id: 257,
  },
  {
    id: 62,
    product_id: "hoverboards3",
    color_id: 4,
    volt_id: 2,
    catalog_id: 257,
  },
  {
    id: 63,
    product_id: "hoverboards3",
    color_id: 4,
    volt_id: 3,
    catalog_id: 257,
  },
  {
    id: 64,
    product_id: "hoverboards4",
    color_id: 5,
    volt_id: 1,
    catalog_id: 262,
  },
  {
    id: 65,
    product_id: "hoverboards4",
    color_id: 5,
    volt_id: 2,
    catalog_id: 262,
  },
  {
    id: 66,
    product_id: "hoverboards4",
    color_id: 5,
    volt_id: 3,
    catalog_id: 262,
  },
  {
    id: 67,
    product_id: "hoverboards5",
    color_id: 6,
    volt_id: 1,
    catalog_id: 331,
  },
  {
    id: 68,
    product_id: "hoverboards5",
    color_id: 6,
    volt_id: 2,
    catalog_id: 331,
  },
  {
    id: 69,
    product_id: "hoverboards5",
    color_id: 6,
    volt_id: 3,
    catalog_id: 331,
  },
  {
    id: 70,
    product_id: "hoverboards6",
    color_id: 7,
    volt_id: 1,
    catalog_id: 256,
  },
  {
    id: 71,
    product_id: "hoverboards6",
    color_id: 7,
    volt_id: 2,
    catalog_id: 256,
  },
  {
    id: 72,
    product_id: "hoverboards6",
    color_id: 7,
    volt_id: 3,
    catalog_id: 256,
  },
  {
    id: 73,
    product_id: "hoverboards7",
    color_id: 8,
    volt_id: 1,
    catalog_id: 255,
  },
  {
    id: 74,
    product_id: "hoverboards7",
    color_id: 8,
    volt_id: 2,
    catalog_id: 255,
  },
  {
    id: 75,
    product_id: "hoverboards7",
    color_id: 8,
    volt_id: 3,
    catalog_id: 255,
  },
  {
    id: 76,
    product_id: "hoverboards8",
    color_id: 9,
    volt_id: 1,
    catalog_id: 259,
  },
  {
    id: 77,
    product_id: "hoverboards8",
    color_id: 9,
    volt_id: 2,
    catalog_id: 259,
  },
  {
    id: 78,
    product_id: "hoverboards8",
    color_id: 9,
    volt_id: 3,
    catalog_id: 259,
  },
  {
    id: 79,
    product_id: "hoverboards9",
    color_id: 10,
    volt_id: 1,
    catalog_id: 263,
  },
  {
    id: 80,
    product_id: "hoverboards9",
    color_id: 10,
    volt_id: 2,
    catalog_id: 263,
  },
  {
    id: 81,
    product_id: "hoverboards9",
    color_id: 10,
    volt_id: 3,
    catalog_id: 263,
  },
  {
    id: 82,
    product_id: "s10",
    color_id: 1,
    volt_id: 1,
    catalog_id: 289,
  },
  {
    id: 83,
    product_id: "s10",
    color_id: 1,
    volt_id: 2,
    catalog_id: 289,
  },
  {
    id: 84,
    product_id: "s10",
    color_id: 1,
    volt_id: 3,
    catalog_id: 289,
  },
  {
    id: 85,
    product_id: "s10",
    color_id: 1,
    volt_id: 1,
    catalog_id: 288,
  },
  {
    id: 86,
    product_id: "s10",
    color_id: 1,
    volt_id: 2,
    catalog_id: 288,
  },
  {
    id: 87,
    product_id: "s10",
    color_id: 1,
    volt_id: 3,
    catalog_id: 288,
  },
  {
    id: 88,
    product_id: "s10",
    color_id: 2,
    volt_id: 1,
    catalog_id: 273,
  },
  {
    id: 89,
    product_id: "s10",
    color_id: 2,
    volt_id: 2,
    catalog_id: 273,
  },
  {
    id: 90,
    product_id: "s10",
    color_id: 2,
    volt_id: 3,
    catalog_id: 273,
  },
  {
    id: 91,
    product_id: "s10",
    color_id: 2,
    volt_id: 1,
    catalog_id: 76,
  },
  {
    id: 92,
    product_id: "s10",
    color_id: 2,
    volt_id: 2,
    catalog_id: 76,
  },
  {
    id: 93,
    product_id: "s10",
    color_id: 2,
    volt_id: 3,
    catalog_id: 76,
  },
  {
    id: 94,
    product_id: "s20",
    color_id: 1,
    volt_id: 1,
    catalog_id: 292,
  },
  {
    id: 95,
    product_id: "s20",
    color_id: 1,
    volt_id: 2,
    catalog_id: 292,
  },
  {
    id: 96,
    product_id: "s20",
    color_id: 1,
    volt_id: 3,
    catalog_id: 292,
  },
  {
    id: 97,
    product_id: "s20",
    color_id: 1,
    volt_id: 1,
    catalog_id: 290,
  },
  {
    id: 98,
    product_id: "s20",
    color_id: 1,
    volt_id: 2,
    catalog_id: 290,
  },
  {
    id: 99,
    product_id: "s20",
    color_id: 1,
    volt_id: 3,
    catalog_id: 290,
  },
  {
    id: 100,
    product_id: "s20",
    color_id: 2,
    volt_id: 1,
    catalog_id: 286,
  },
  {
    id: 101,
    product_id: "s20",
    color_id: 2,
    volt_id: 2,
    catalog_id: 286,
  },
  {
    id: 102,
    product_id: "s20",
    color_id: 2,
    volt_id: 3,
    catalog_id: 286,
  },
  {
    id: 103,
    product_id: "s20",
    color_id: 2,
    volt_id: 1,
    catalog_id: 287,
  },
  {
    id: 104,
    product_id: "s20",
    color_id: 2,
    volt_id: 2,
    catalog_id: 287,
  },
  {
    id: 105,
    product_id: "s20",
    color_id: 2,
    volt_id: 3,
    catalog_id: 287,
  },
  {
    id: 106,
    product_id: "s30",
    color_id: 11,
    volt_id: 1,
    catalog_id: 72,
  },
  {
    id: 107,
    product_id: "s30",
    color_id: 11,
    volt_id: 2,
    catalog_id: 72,
  },
  {
    id: 108,
    product_id: "s30",
    color_id: 11,
    volt_id: 3,
    catalog_id: 72,
  },
  {
    id: 109,
    product_id: "s30",
    color_id: 11,
    volt_id: 1,
    catalog_id: 88,
  },
  {
    id: 110,
    product_id: "s30",
    color_id: 11,
    volt_id: 2,
    catalog_id: 88,
  },
  {
    id: 111,
    product_id: "s30",
    color_id: 11,
    volt_id: 3,
    catalog_id: 88,
  },
  {
    id: 112,
    product_id: "s40",
    color_id: 1,
    volt_id: 1,
    catalog_id: 84,
  },
  {
    id: 113,
    product_id: "s40",
    color_id: 1,
    volt_id: 2,
    catalog_id: 84,
  },
  {
    id: 114,
    product_id: "s40",
    color_id: 1,
    volt_id: 3,
    catalog_id: 84,
  },
  {
    id: 115,
    product_id: "s40",
    color_id: 1,
    volt_id: 1,
    catalog_id: 279,
  },
  {
    id: 116,
    product_id: "s40",
    color_id: 1,
    volt_id: 2,
    catalog_id: 279,
  },
  {
    id: 117,
    product_id: "s40",
    color_id: 1,
    volt_id: 3,
    catalog_id: 279,
  },
  {
    id: 118,
    product_id: "G10",
    color_id: 1,
    volt_id: 1,
    catalog_id: 55,
  },
  {
    id: 119,
    product_id: "G10",
    color_id: 1,
    volt_id: 2,
    catalog_id: 55,
  },
  {
    id: 120,
    product_id: "G10",
    color_id: 1,
    volt_id: 3,
    catalog_id: 55,
  },
  {
    id: 121,
    product_id: "G10",
    color_id: 1,
    volt_id: 1,
    catalog_id: 278,
  },
  {
    id: 122,
    product_id: "G10",
    color_id: 1,
    volt_id: 2,
    catalog_id: 278,
  },
  {
    id: 123,
    product_id: "G10",
    color_id: 1,
    volt_id: 3,
    catalog_id: 278,
  },
  {
    id: 124,
    product_id: "G20",
    color_id: 1,
    volt_id: 1,
    catalog_id: 53,
  },
  {
    id: 125,
    product_id: "G20",
    color_id: 1,
    volt_id: 2,
    catalog_id: 53,
  },
  {
    id: 126,
    product_id: "G20",
    color_id: 1,
    volt_id: 3,
    catalog_id: 53,
  },
  {
    id: 127,
    product_id: "G20",
    color_id: 1,
    volt_id: 1,
    catalog_id: 285,
  },
  {
    id: 128,
    product_id: "G20",
    color_id: 1,
    volt_id: 2,
    catalog_id: 285,
  },
  {
    id: 129,
    product_id: "G20",
    color_id: 1,
    volt_id: 3,
    catalog_id: 285,
  },
  {
    id: 130,
    product_id: "G30",
    color_id: 1,
    volt_id: 1,
    catalog_id: 275,
  },
  {
    id: 131,
    product_id: "G30",
    color_id: 1,
    volt_id: 2,
    catalog_id: 275,
  },
  {
    id: 132,
    product_id: "G30",
    color_id: 1,
    volt_id: 3,
    catalog_id: 275,
  },
  {
    id: 133,
    product_id: "G30",
    color_id: 1,
    volt_id: 1,
    catalog_id: 63,
  },
  {
    id: 134,
    product_id: "G30",
    color_id: 1,
    volt_id: 2,
    catalog_id: 63,
  },
  {
    id: 135,
    product_id: "G30",
    color_id: 1,
    volt_id: 3,
    catalog_id: 63,
  },
  {
    id: 136,
    product_id: "G40",
    color_id: 1,
    volt_id: 1,
    catalog_id: 42,
  },
  {
    id: 137,
    product_id: "G40",
    color_id: 1,
    volt_id: 2,
    catalog_id: 42,
  },
  {
    id: 138,
    product_id: "G40",
    color_id: 1,
    volt_id: 3,
    catalog_id: 42,
  },
  {
    id: 139,
    product_id: "G40",
    color_id: 1,
    volt_id: 1,
    catalog_id: 41,
  },
  {
    id: 140,
    product_id: "G40",
    color_id: 1,
    volt_id: 2,
    catalog_id: 41,
  },
  {
    id: 141,
    product_id: "G40",
    color_id: 1,
    volt_id: 3,
    catalog_id: 41,
  },
  {
    id: 142,
    product_id: "G50",
    color_id: 1,
    volt_id: 1,
    catalog_id: 277,
  },
  {
    id: 143,
    product_id: "G50",
    color_id: 1,
    volt_id: 2,
    catalog_id: 277,
  },
  {
    id: 144,
    product_id: "G50",
    color_id: 1,
    volt_id: 3,
    catalog_id: 277,
  },
  {
    id: 145,
    product_id: "G50",
    color_id: 1,
    volt_id: 1,
    catalog_id: 106,
  },
  {
    id: 146,
    product_id: "G50",
    color_id: 1,
    volt_id: 2,
    catalog_id: 106,
  },
  {
    id: 147,
    product_id: "G50",
    color_id: 1,
    volt_id: 3,
    catalog_id: 106,
  },
  {
    id: 148,
    product_id: "C10",
    color_id: 2,
    volt_id: 1,
    catalog_id: 300,
  },
  {
    id: 149,
    product_id: "C10",
    color_id: 2,
    volt_id: 2,
    catalog_id: 300,
  },
  {
    id: 150,
    product_id: "C10",
    color_id: 2,
    volt_id: 3,
    catalog_id: 300,
  },
  {
    id: 151,
    product_id: "C10",
    color_id: 2,
    volt_id: 1,
    catalog_id: 282,
  },
  {
    id: 152,
    product_id: "C10",
    color_id: 2,
    volt_id: 2,
    catalog_id: 282,
  },
  {
    id: 153,
    product_id: "C10",
    color_id: 2,
    volt_id: 3,
    catalog_id: 282,
  },
  {
    id: 154,
    product_id: "C20",
    color_id: 1,
    volt_id: 1,
    catalog_id: 301,
  },
  {
    id: 155,
    product_id: "C20",
    color_id: 1,
    volt_id: 2,
    catalog_id: 301,
  },
  {
    id: 156,
    product_id: "C20",
    color_id: 1,
    volt_id: 3,
    catalog_id: 301,
  },
  {
    id: 157,
    product_id: "C20",
    color_id: 1,
    volt_id: 1,
    catalog_id: 281,
  },
  {
    id: 158,
    product_id: "C20",
    color_id: 1,
    volt_id: 2,
    catalog_id: 281,
  },
  {
    id: 159,
    product_id: "C20",
    color_id: 1,
    volt_id: 3,
    catalog_id: 281,
  },
  {
    id: 160,
    product_id: "C30",
    color_id: 1,
    volt_id: 1,
    catalog_id: 299,
  },
  {
    id: 161,
    product_id: "C30",
    color_id: 1,
    volt_id: 2,
    catalog_id: 299,
  },
  {
    id: 162,
    product_id: "C30",
    color_id: 1,
    volt_id: 3,
    catalog_id: 299,
  },
  {
    id: 163,
    product_id: "C30",
    color_id: 1,
    volt_id: 1,
    catalog_id: 39,
  },
  {
    id: 164,
    product_id: "C30",
    color_id: 1,
    volt_id: 2,
    catalog_id: 39,
  },
  {
    id: 165,
    product_id: "C30",
    color_id: 1,
    volt_id: 3,
    catalog_id: 39,
  },
  {
    id: 166,
    product_id: "T10",
    color_id: 12,
    volt_id: 1,
    catalog_id: 47,
  },
  {
    id: 167,
    product_id: "T10",
    color_id: 12,
    volt_id: 2,
    catalog_id: 47,
  },
  {
    id: 168,
    product_id: "T10",
    color_id: 12,
    volt_id: 3,
    catalog_id: 47,
  },
  {
    id: 169,
    product_id: "T10",
    color_id: 12,
    volt_id: 1,
    catalog_id: 46,
  },
  {
    id: 170,
    product_id: "T10",
    color_id: 12,
    volt_id: 2,
    catalog_id: 46,
  },
  {
    id: 171,
    product_id: "T10",
    color_id: 12,
    volt_id: 3,
    catalog_id: 46,
  },
  {
    id: 172,
    product_id: "T20",
    color_id: 2,
    volt_id: 1,
    catalog_id: 208,
  },
  {
    id: 173,
    product_id: "T20",
    color_id: 2,
    volt_id: 2,
    catalog_id: 208,
  },
  {
    id: 174,
    product_id: "T20",
    color_id: 2,
    volt_id: 3,
    catalog_id: 208,
  },
  {
    id: 175,
    product_id: "T20",
    color_id: 2,
    volt_id: 1,
    catalog_id: 48,
  },
  {
    id: 176,
    product_id: "T20",
    color_id: 2,
    volt_id: 2,
    catalog_id: 48,
  },
  {
    id: 177,
    product_id: "T20",
    color_id: 2,
    volt_id: 3,
    catalog_id: 48,
  },
  {
    id: 178,
    product_id: "T30",
    color_id: 1,
    volt_id: 1,
    catalog_id: 45,
  },
  {
    id: 179,
    product_id: "T30",
    color_id: 1,
    volt_id: 2,
    catalog_id: 45,
  },
  {
    id: 180,
    product_id: "T30",
    color_id: 1,
    volt_id: 3,
    catalog_id: 45,
  },
  {
    id: 181,
    product_id: "T30",
    color_id: 1,
    volt_id: 1,
    catalog_id: 44,
  },
  {
    id: 182,
    product_id: "T30",
    color_id: 1,
    volt_id: 2,
    catalog_id: 44,
  },
  {
    id: 183,
    product_id: "T30",
    color_id: 1,
    volt_id: 3,
    catalog_id: 44,
  },
  {
    id: 184,
    product_id: "E10",
    color_id: 11,
    volt_id: 1,
    catalog_id: 271,
  },
  {
    id: 185,
    product_id: "E10",
    color_id: 11,
    volt_id: 2,
    catalog_id: 271,
  },
  {
    id: 186,
    product_id: "E10",
    color_id: 11,
    volt_id: 3,
    catalog_id: 271,
  },
  {
    id: 187,
    product_id: "E10",
    color_id: 11,
    volt_id: 1,
    catalog_id: 272,
  },
  {
    id: 188,
    product_id: "E10",
    color_id: 11,
    volt_id: 2,
    catalog_id: 272,
  },
  {
    id: 189,
    product_id: "E10",
    color_id: 11,
    volt_id: 3,
    catalog_id: 272,
  },
  {
    id: 190,
    product_id: "F10",
    color_id: 13,
    volt_id: 1,
    catalog_id: 283,
  },
  {
    id: 191,
    product_id: "F10",
    color_id: 13,
    volt_id: 2,
    catalog_id: 283,
  },
  {
    id: 192,
    product_id: "F10",
    color_id: 13,
    volt_id: 3,
    catalog_id: 283,
  },
  {
    id: 193,
    product_id: "F10",
    color_id: 13,
    volt_id: 1,
    catalog_id: 122,
  },
  {
    id: 194,
    product_id: "F10",
    color_id: 13,
    volt_id: 2,
    catalog_id: 122,
  },
  {
    id: 195,
    product_id: "F10",
    color_id: 13,
    volt_id: 3,
    catalog_id: 122,
  },
  {
    id: 196,
    product_id: "F20",
    color_id: 13,
    volt_id: 1,
    catalog_id: 291,
  },
  {
    id: 197,
    product_id: "F20",
    color_id: 13,
    volt_id: 2,
    catalog_id: 291,
  },
  {
    id: 198,
    product_id: "F20",
    color_id: 13,
    volt_id: 3,
    catalog_id: 291,
  },
  {
    id: 199,
    product_id: "F20",
    color_id: 13,
    volt_id: 1,
    catalog_id: 293,
  },
  {
    id: 200,
    product_id: "F20",
    color_id: 13,
    volt_id: 2,
    catalog_id: 293,
  },
  {
    id: 201,
    product_id: "F20",
    color_id: 13,
    volt_id: 3,
    catalog_id: 293,
  },
  {
    id: 202,
    product_id: "F30",
    color_id: 14,
    volt_id: 1,
    catalog_id: 102,
  },
  {
    id: 203,
    product_id: "F30",
    color_id: 14,
    volt_id: 2,
    catalog_id: 102,
  },
  {
    id: 204,
    product_id: "F30",
    color_id: 14,
    volt_id: 3,
    catalog_id: 102,
  },
  {
    id: 205,
    product_id: "F40",
    color_id: 15,
    volt_id: 1,
    catalog_id: 123,
  },
  {
    id: 206,
    product_id: "F40",
    color_id: 15,
    volt_id: 2,
    catalog_id: 123,
  },
  {
    id: 207,
    product_id: "F40",
    color_id: 15,
    volt_id: 3,
    catalog_id: 123,
  },
  {
    id: 208,
    product_id: "F40",
    color_id: 15,
    volt_id: 1,
    catalog_id: 119,
  },
  {
    id: 209,
    product_id: "F40",
    color_id: 15,
    volt_id: 2,
    catalog_id: 119,
  },
  {
    id: 210,
    product_id: "F40",
    color_id: 15,
    volt_id: 3,
    catalog_id: 119,
  },
  {
    id: 211,
    product_id: "F50",
    color_id: 1,
    volt_id: 1,
    catalog_id: 177,
  },
  {
    id: 212,
    product_id: "F50",
    color_id: 1,
    volt_id: 2,
    catalog_id: 177,
  },
  {
    id: 213,
    product_id: "F50",
    color_id: 1,
    volt_id: 3,
    catalog_id: 177,
  },
  {
    id: 214,
    product_id: "F50",
    color_id: 1,
    volt_id: 1,
    catalog_id: 143,
  },
  {
    id: 215,
    product_id: "F50",
    color_id: 1,
    volt_id: 2,
    catalog_id: 143,
  },
  {
    id: 216,
    product_id: "F50",
    color_id: 1,
    volt_id: 3,
    catalog_id: 143,
  },
  {
    id: 217,
    product_id: "L10",
    color_id: 2,
    volt_id: 1,
    catalog_id: 73,
  },
  {
    id: 218,
    product_id: "L10",
    color_id: 2,
    volt_id: 2,
    catalog_id: 73,
  },
  {
    id: 219,
    product_id: "L10",
    color_id: 2,
    volt_id: 3,
    catalog_id: 73,
  },
  {
    id: 220,
    product_id: "L10",
    color_id: 2,
    volt_id: 1,
    catalog_id: 142,
  },
  {
    id: 221,
    product_id: "L10",
    color_id: 2,
    volt_id: 2,
    catalog_id: 142,
  },
  {
    id: 222,
    product_id: "L10",
    color_id: 2,
    volt_id: 3,
    catalog_id: 142,
  },
  {
    id: 223,
    product_id: "L20",
    color_id: 2,
    volt_id: 1,
    catalog_id: 157,
  },
  {
    id: 224,
    product_id: "L20",
    color_id: 2,
    volt_id: 2,
    catalog_id: 157,
  },
  {
    id: 225,
    product_id: "L20",
    color_id: 2,
    volt_id: 3,
    catalog_id: 157,
  },
  {
    id: 226,
    product_id: "L20",
    color_id: 2,
    volt_id: 1,
    catalog_id: 100,
  },
  {
    id: 227,
    product_id: "L20",
    color_id: 2,
    volt_id: 2,
    catalog_id: 100,
  },
  {
    id: 228,
    product_id: "L20",
    color_id: 2,
    volt_id: 3,
    catalog_id: 100,
  },
  {
    id: 229,
    product_id: "L30",
    color_id: 1,
    volt_id: 1,
    catalog_id: 83,
  },
  {
    id: 230,
    product_id: "L30",
    color_id: 1,
    volt_id: 2,
    catalog_id: 83,
  },
  {
    id: 231,
    product_id: "L30",
    color_id: 1,
    volt_id: 3,
    catalog_id: 83,
  },
  {
    id: 232,
    product_id: "L30",
    color_id: 1,
    volt_id: 1,
    catalog_id: 99,
  },
  {
    id: 233,
    product_id: "L30",
    color_id: 1,
    volt_id: 2,
    catalog_id: 99,
  },
  {
    id: 234,
    product_id: "L30",
    color_id: 1,
    volt_id: 3,
    catalog_id: 99,
  },
  {
    id: 235,
    product_id: "L40",
    color_id: 1,
    volt_id: 1,
    catalog_id: 49,
  },
  {
    id: 236,
    product_id: "L40",
    color_id: 1,
    volt_id: 2,
    catalog_id: 49,
  },
  {
    id: 237,
    product_id: "L40",
    color_id: 1,
    volt_id: 3,
    catalog_id: 49,
  },
  {
    id: 238,
    product_id: "L40",
    color_id: 1,
    volt_id: 1,
    catalog_id: 98,
  },
  {
    id: 239,
    product_id: "L40",
    color_id: 1,
    volt_id: 2,
    catalog_id: 98,
  },
  {
    id: 240,
    product_id: "L40",
    color_id: 1,
    volt_id: 3,
    catalog_id: 98,
  },
  {
    id: 241,
    product_id: "603D",
    color_id: 1,
    volt_id: 1,
    catalog_id: 194,
  },
  {
    id: 242,
    product_id: "603D",
    color_id: 1,
    volt_id: 2,
    catalog_id: 194,
  },
  {
    id: 243,
    product_id: "603D",
    color_id: 1,
    volt_id: 3,
    catalog_id: 194,
  },
  {
    id: 244,
    product_id: "HB40",
    color_id: 1,
    volt_id: 1,
    catalog_id: 195,
  },
  {
    id: 245,
    product_id: "HB40",
    color_id: 1,
    volt_id: 2,
    catalog_id: 195,
  },
  {
    id: 246,
    product_id: "HB40",
    color_id: 1,
    volt_id: 3,
    catalog_id: 195,
  },
  {
    id: 247,
    product_id: "HD008",
    color_id: 1,
    volt_id: 1,
    catalog_id: 196,
  },
  {
    id: 248,
    product_id: "HD008",
    color_id: 1,
    volt_id: 2,
    catalog_id: 196,
  },
  {
    id: 249,
    product_id: "HD008",
    color_id: 1,
    volt_id: 3,
    catalog_id: 196,
  },
  {
    id: 250,
    product_id: "RFCD865",
    color_id: 16,
    volt_id: 1,
    catalog_id: 197,
  },
  {
    id: 251,
    product_id: "RFCD865",
    color_id: 16,
    volt_id: 2,
    catalog_id: 197,
  },
  {
    id: 252,
    product_id: "RFCD865",
    color_id: 16,
    volt_id: 3,
    catalog_id: 197,
  },
  {
    id: 253,
    product_id: "B10",
    color_id: 17,
    volt_id: 1,
    catalog_id: 178,
  },
  {
    id: 254,
    product_id: "B10",
    color_id: 17,
    volt_id: 2,
    catalog_id: 178,
  },
  {
    id: 255,
    product_id: "B10",
    color_id: 17,
    volt_id: 3,
    catalog_id: 178,
  },
  {
    id: 256,
    product_id: "B10",
    color_id: 17,
    volt_id: 1,
    catalog_id: 56,
  },
  {
    id: 257,
    product_id: "B10",
    color_id: 17,
    volt_id: 2,
    catalog_id: 56,
  },
  {
    id: 258,
    product_id: "B10",
    color_id: 17,
    volt_id: 3,
    catalog_id: 56,
  },
  {
    id: 259,
    product_id: "B20",
    color_id: 18,
    volt_id: 1,
    catalog_id: 166,
  },
  {
    id: 260,
    product_id: "B20",
    color_id: 18,
    volt_id: 2,
    catalog_id: 166,
  },
  {
    id: 261,
    product_id: "B20",
    color_id: 18,
    volt_id: 3,
    catalog_id: 166,
  },
  {
    id: 262,
    product_id: "B20",
    color_id: 18,
    volt_id: 1,
    catalog_id: 303,
  },
  {
    id: 263,
    product_id: "B20",
    color_id: 18,
    volt_id: 2,
    catalog_id: 303,
  },
  {
    id: 264,
    product_id: "B20",
    color_id: 18,
    volt_id: 3,
    catalog_id: 303,
  },
  {
    id: 265,
    product_id: "B30",
    color_id: 1,
    volt_id: 1,
    catalog_id: 171,
  },
  {
    id: 266,
    product_id: "B30",
    color_id: 1,
    volt_id: 2,
    catalog_id: 171,
  },
  {
    id: 267,
    product_id: "B30",
    color_id: 1,
    volt_id: 3,
    catalog_id: 171,
  },
  {
    id: 268,
    product_id: "B30",
    color_id: 1,
    volt_id: 1,
    catalog_id: 57,
  },
  {
    id: 269,
    product_id: "B30",
    color_id: 1,
    volt_id: 2,
    catalog_id: 57,
  },
  {
    id: 270,
    product_id: "B30",
    color_id: 1,
    volt_id: 3,
    catalog_id: 57,
  },
  {
    id: 271,
    product_id: "A10",
    color_id: 12,
    volt_id: 1,
    catalog_id: 67,
  },
  {
    id: 272,
    product_id: "A10",
    color_id: 12,
    volt_id: 2,
    catalog_id: 67,
  },
  {
    id: 273,
    product_id: "A10",
    color_id: 12,
    volt_id: 3,
    catalog_id: 67,
  },
  {
    id: 274,
    product_id: "A10",
    color_id: 12,
    volt_id: 1,
    catalog_id: 202,
  },
  {
    id: 275,
    product_id: "A10",
    color_id: 12,
    volt_id: 2,
    catalog_id: 202,
  },
  {
    id: 276,
    product_id: "A10",
    color_id: 12,
    volt_id: 3,
    catalog_id: 202,
  },
  {
    id: 277,
    product_id: "P10",
    color_id: 11,
    volt_id: 1,
    catalog_id: 280,
  },
  {
    id: 278,
    product_id: "P10",
    color_id: 11,
    volt_id: 2,
    catalog_id: 280,
  },
  {
    id: 279,
    product_id: "P10",
    color_id: 11,
    volt_id: 3,
    catalog_id: 280,
  },
  {
    id: 280,
    product_id: "P10",
    color_id: 11,
    volt_id: 1,
    catalog_id: 52,
  },
  {
    id: 281,
    product_id: "P10",
    color_id: 11,
    volt_id: 2,
    catalog_id: 52,
  },
  {
    id: 282,
    product_id: "P10",
    color_id: 11,
    volt_id: 3,
    catalog_id: 52,
  },
  {
    id: 283,
    product_id: "W10",
    color_id: 2,
    volt_id: 1,
    catalog_id: 51,
  },
  {
    id: 284,
    product_id: "W10",
    color_id: 2,
    volt_id: 2,
    catalog_id: 51,
  },
  {
    id: 285,
    product_id: "W10",
    color_id: 2,
    volt_id: 3,
    catalog_id: 51,
  },
  {
    id: 286,
    product_id: "W10",
    color_id: 2,
    volt_id: 1,
    catalog_id: 50,
  },
  {
    id: 287,
    product_id: "W10",
    color_id: 2,
    volt_id: 2,
    catalog_id: 50,
  },
  {
    id: 288,
    product_id: "W10",
    color_id: 2,
    volt_id: 3,
    catalog_id: 50,
  },
];

const ALL_PHOTOS = [
  {
    id: 1,
    variant_id: 1,
    url: "/productos/tvs/IN3200TV-1.webp",
    order: 0,
  },
  {
    id: 2,
    variant_id: 1,
    url: "/productos/tvs/IN3200TV-2.webp",
    order: 1,
  },
  {
    id: 3,
    variant_id: 1,
    url: "/productos/tvs/IN3200TV-3.webp",
    order: 2,
  },
  {
    id: 4,
    variant_id: 2,
    url: "/productos/tvs/IN3200TV-1.webp",
    order: 0,
  },
  {
    id: 5,
    variant_id: 2,
    url: "/productos/tvs/IN3200TV-2.webp",
    order: 1,
  },
  {
    id: 6,
    variant_id: 2,
    url: "/productos/tvs/IN3200TV-3.webp",
    order: 2,
  },
  {
    id: 7,
    variant_id: 3,
    url: "/productos/tvs/IN3200TV-1.webp",
    order: 0,
  },
  {
    id: 8,
    variant_id: 3,
    url: "/productos/tvs/IN3200TV-2.webp",
    order: 1,
  },
  {
    id: 9,
    variant_id: 3,
    url: "/productos/tvs/IN3200TV-3.webp",
    order: 2,
  },
  {
    id: 10,
    variant_id: 4,
    url: "/productos/tvs/IN4300TV-1.webp",
    order: 0,
  },
  {
    id: 11,
    variant_id: 4,
    url: "/productos/tvs/IN4300TV-2.webp",
    order: 1,
  },
  {
    id: 12,
    variant_id: 4,
    url: "/productos/tvs/IN4300TV-3.webp",
    order: 2,
  },
  {
    id: 13,
    variant_id: 4,
    url: "/productos/tvs/IN4300TV-4.webp",
    order: 3,
  },
  {
    id: 14,
    variant_id: 5,
    url: "/productos/tvs/IN4300TV-1.webp",
    order: 0,
  },
  {
    id: 15,
    variant_id: 5,
    url: "/productos/tvs/IN4300TV-2.webp",
    order: 1,
  },
  {
    id: 16,
    variant_id: 5,
    url: "/productos/tvs/IN4300TV-3.webp",
    order: 2,
  },
  {
    id: 17,
    variant_id: 5,
    url: "/productos/tvs/IN4300TV-4.webp",
    order: 3,
  },
  {
    id: 18,
    variant_id: 6,
    url: "/productos/tvs/IN4300TV-1.webp",
    order: 0,
  },
  {
    id: 19,
    variant_id: 6,
    url: "/productos/tvs/IN4300TV-2.webp",
    order: 1,
  },
  {
    id: 20,
    variant_id: 6,
    url: "/productos/tvs/IN4300TV-3.webp",
    order: 2,
  },
  {
    id: 21,
    variant_id: 6,
    url: "/productos/tvs/IN4300TV-4.webp",
    order: 3,
  },
  {
    id: 22,
    variant_id: 7,
    url: "/productos/tvs/IN5000TV-1.webp",
    order: 0,
  },
  {
    id: 23,
    variant_id: 7,
    url: "/productos/tvs/IN5000TV-2.webp",
    order: 1,
  },
  {
    id: 24,
    variant_id: 7,
    url: "/productos/tvs/IN5000TV-3.webp",
    order: 2,
  },
  {
    id: 25,
    variant_id: 7,
    url: "/productos/tvs/IN5000TV-4.webp",
    order: 3,
  },
  {
    id: 26,
    variant_id: 8,
    url: "/productos/tvs/IN5000TV-1.webp",
    order: 0,
  },
  {
    id: 27,
    variant_id: 8,
    url: "/productos/tvs/IN5000TV-2.webp",
    order: 1,
  },
  {
    id: 28,
    variant_id: 8,
    url: "/productos/tvs/IN5000TV-3.webp",
    order: 2,
  },
  {
    id: 29,
    variant_id: 8,
    url: "/productos/tvs/IN5000TV-4.webp",
    order: 3,
  },
  {
    id: 30,
    variant_id: 9,
    url: "/productos/tvs/IN5000TV-1.webp",
    order: 0,
  },
  {
    id: 31,
    variant_id: 9,
    url: "/productos/tvs/IN5000TV-2.webp",
    order: 1,
  },
  {
    id: 32,
    variant_id: 9,
    url: "/productos/tvs/IN5000TV-3.webp",
    order: 2,
  },
  {
    id: 33,
    variant_id: 9,
    url: "/productos/tvs/IN5000TV-4.webp",
    order: 3,
  },
  {
    id: 34,
    variant_id: 10,
    url: "/productos/tvs/IN5500TV-1.webp",
    order: 0,
  },
  {
    id: 35,
    variant_id: 10,
    url: "/productos/tvs/IN5500TV-2.webp",
    order: 1,
  },
  {
    id: 36,
    variant_id: 10,
    url: "/productos/tvs/IN5500TV-3.webp",
    order: 2,
  },
  {
    id: 37,
    variant_id: 10,
    url: "/productos/tvs/IN5500TV-4.webp",
    order: 3,
  },
  {
    id: 38,
    variant_id: 11,
    url: "/productos/tvs/IN5500TV-1.webp",
    order: 0,
  },
  {
    id: 39,
    variant_id: 11,
    url: "/productos/tvs/IN5500TV-2.webp",
    order: 1,
  },
  {
    id: 40,
    variant_id: 11,
    url: "/productos/tvs/IN5500TV-3.webp",
    order: 2,
  },
  {
    id: 41,
    variant_id: 11,
    url: "/productos/tvs/IN5500TV-4.webp",
    order: 3,
  },
  {
    id: 42,
    variant_id: 12,
    url: "/productos/tvs/IN5500TV-1.webp",
    order: 0,
  },
  {
    id: 43,
    variant_id: 12,
    url: "/productos/tvs/IN5500TV-2.webp",
    order: 1,
  },
  {
    id: 44,
    variant_id: 12,
    url: "/productos/tvs/IN5500TV-3.webp",
    order: 2,
  },
  {
    id: 45,
    variant_id: 12,
    url: "/productos/tvs/IN5500TV-4.webp",
    order: 3,
  },
  {
    id: 46,
    variant_id: 13,
    url: "/productos/tvs/IN6500TV-1.webp",
    order: 0,
  },
  {
    id: 47,
    variant_id: 13,
    url: "/productos/tvs/IN6500TV-2.webp",
    order: 1,
  },
  {
    id: 48,
    variant_id: 13,
    url: "/productos/tvs/IN6500TV-3.webp",
    order: 2,
  },
  {
    id: 49,
    variant_id: 13,
    url: "/productos/tvs/IN6500TV-4.webp",
    order: 3,
  },
  {
    id: 50,
    variant_id: 14,
    url: "/productos/tvs/IN6500TV-1.webp",
    order: 0,
  },
  {
    id: 51,
    variant_id: 14,
    url: "/productos/tvs/IN6500TV-2.webp",
    order: 1,
  },
  {
    id: 52,
    variant_id: 14,
    url: "/productos/tvs/IN6500TV-3.webp",
    order: 2,
  },
  {
    id: 53,
    variant_id: 14,
    url: "/productos/tvs/IN6500TV-4.webp",
    order: 3,
  },
  {
    id: 54,
    variant_id: 15,
    url: "/productos/tvs/IN6500TV-1.webp",
    order: 0,
  },
  {
    id: 55,
    variant_id: 15,
    url: "/productos/tvs/IN6500TV-2.webp",
    order: 1,
  },
  {
    id: 56,
    variant_id: 15,
    url: "/productos/tvs/IN6500TV-3.webp",
    order: 2,
  },
  {
    id: 57,
    variant_id: 15,
    url: "/productos/tvs/IN6500TV-4.webp",
    order: 3,
  },
  {
    id: 58,
    variant_id: 16,
    url: "/productos/tvs/IN7500TV-1.webp",
    order: 0,
  },
  {
    id: 59,
    variant_id: 16,
    url: "/productos/tvs/IN7500TV-2.webp",
    order: 1,
  },
  {
    id: 60,
    variant_id: 16,
    url: "/productos/tvs/IN7500TV-3.webp",
    order: 2,
  },
  {
    id: 61,
    variant_id: 16,
    url: "/productos/tvs/IN7500TV-4.webp",
    order: 3,
  },
  {
    id: 62,
    variant_id: 17,
    url: "/productos/tvs/IN7500TV-1.webp",
    order: 0,
  },
  {
    id: 63,
    variant_id: 17,
    url: "/productos/tvs/IN7500TV-2.webp",
    order: 1,
  },
  {
    id: 64,
    variant_id: 17,
    url: "/productos/tvs/IN7500TV-3.webp",
    order: 2,
  },
  {
    id: 65,
    variant_id: 17,
    url: "/productos/tvs/IN7500TV-4.webp",
    order: 3,
  },
  {
    id: 66,
    variant_id: 18,
    url: "/productos/tvs/IN7500TV-1.webp",
    order: 0,
  },
  {
    id: 67,
    variant_id: 18,
    url: "/productos/tvs/IN7500TV-2.webp",
    order: 1,
  },
  {
    id: 68,
    variant_id: 18,
    url: "/productos/tvs/IN7500TV-3.webp",
    order: 2,
  },
  {
    id: 69,
    variant_id: 18,
    url: "/productos/tvs/IN7500TV-4.webp",
    order: 3,
  },
  {
    id: 70,
    variant_id: 19,
    url: "/productos/tvs/IN8500TV-1.webp",
    order: 0,
  },
  {
    id: 71,
    variant_id: 19,
    url: "/productos/tvs/IN8500TV-2.webp",
    order: 1,
  },
  {
    id: 72,
    variant_id: 19,
    url: "/productos/tvs/IN8500TV-3.webp",
    order: 2,
  },
  {
    id: 73,
    variant_id: 19,
    url: "/productos/tvs/IN8500TV-4.webp",
    order: 3,
  },
  {
    id: 74,
    variant_id: 20,
    url: "/productos/tvs/IN8500TV-1.webp",
    order: 0,
  },
  {
    id: 75,
    variant_id: 20,
    url: "/productos/tvs/IN8500TV-2.webp",
    order: 1,
  },
  {
    id: 76,
    variant_id: 20,
    url: "/productos/tvs/IN8500TV-3.webp",
    order: 2,
  },
  {
    id: 77,
    variant_id: 20,
    url: "/productos/tvs/IN8500TV-4.webp",
    order: 3,
  },
  {
    id: 78,
    variant_id: 21,
    url: "/productos/tvs/IN8500TV-1.webp",
    order: 0,
  },
  {
    id: 79,
    variant_id: 21,
    url: "/productos/tvs/IN8500TV-2.webp",
    order: 1,
  },
  {
    id: 80,
    variant_id: 21,
    url: "/productos/tvs/IN8500TV-3.webp",
    order: 2,
  },
  {
    id: 81,
    variant_id: 21,
    url: "/productos/tvs/IN8500TV-4.webp",
    order: 3,
  },
  {
    id: 82,
    variant_id: 22,
    url: "/productos/scooters/8.5-v1-1.webp",
    order: 0,
  },
  {
    id: 83,
    variant_id: 23,
    url: "/productos/scooters/8.5-v1-1.webp",
    order: 0,
  },
  {
    id: 84,
    variant_id: 24,
    url: "/productos/scooters/8.5-v1-1.webp",
    order: 0,
  },
  {
    id: 85,
    variant_id: 25,
    url: "/productos/scooters/8.5-v1-1.webp",
    order: 0,
  },
  {
    id: 86,
    variant_id: 26,
    url: "/productos/scooters/8.5-v1-1.webp",
    order: 0,
  },
  {
    id: 87,
    variant_id: 27,
    url: "/productos/scooters/8.5-v1-1.webp",
    order: 0,
  },
  {
    id: 88,
    variant_id: 28,
    url: "/productos/scooters/10.5pro-v1-1.webp",
    order: 0,
  },
  {
    id: 89,
    variant_id: 29,
    url: "/productos/scooters/10.5pro-v1-1.webp",
    order: 0,
  },
  {
    id: 90,
    variant_id: 30,
    url: "/productos/scooters/10.5pro-v1-1.webp",
    order: 0,
  },
  {
    id: 91,
    variant_id: 31,
    url: "/productos/scooters/cross-v1-1.webp",
    order: 0,
  },
  {
    id: 92,
    variant_id: 32,
    url: "/productos/scooters/cross-v1-1.webp",
    order: 0,
  },
  {
    id: 93,
    variant_id: 33,
    url: "/productos/scooters/cross-v1-1.webp",
    order: 0,
  },
  {
    id: 94,
    variant_id: 34,
    url: "/productos/scooters/crosspro-v1-1.webp",
    order: 0,
  },
  {
    id: 95,
    variant_id: 35,
    url: "/productos/scooters/crosspro-v1-1.webp",
    order: 0,
  },
  {
    id: 96,
    variant_id: 36,
    url: "/productos/scooters/crosspro-v1-1.webp",
    order: 0,
  },
  {
    id: 97,
    variant_id: 37,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 98,
    variant_id: 38,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 99,
    variant_id: 39,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 100,
    variant_id: 40,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 101,
    variant_id: 41,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 102,
    variant_id: 42,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 103,
    variant_id: 43,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 104,
    variant_id: 44,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 105,
    variant_id: 45,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 106,
    variant_id: 46,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 107,
    variant_id: 47,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 108,
    variant_id: 48,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 109,
    variant_id: 49,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 110,
    variant_id: 50,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 111,
    variant_id: 51,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 112,
    variant_id: 52,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 113,
    variant_id: 53,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 114,
    variant_id: 54,
    url: "/productos/aires/general.webp",
    order: 0,
  },
  {
    id: 115,
    variant_id: 55,
    url: "/productos/hoverboards/hoverboards1-1.webp",
    order: 0,
  },
  {
    id: 116,
    variant_id: 55,
    url: "/productos/hoverboards/hoverboards1-2.webp",
    order: 1,
  },
  {
    id: 117,
    variant_id: 55,
    url: "/productos/hoverboards/hoverboards1-3.webp",
    order: 2,
  },
  {
    id: 118,
    variant_id: 56,
    url: "/productos/hoverboards/hoverboards1-1.webp",
    order: 0,
  },
  {
    id: 119,
    variant_id: 56,
    url: "/productos/hoverboards/hoverboards1-2.webp",
    order: 1,
  },
  {
    id: 120,
    variant_id: 56,
    url: "/productos/hoverboards/hoverboards1-3.webp",
    order: 2,
  },
  {
    id: 121,
    variant_id: 57,
    url: "/productos/hoverboards/hoverboards1-1.webp",
    order: 0,
  },
  {
    id: 122,
    variant_id: 57,
    url: "/productos/hoverboards/hoverboards1-2.webp",
    order: 1,
  },
  {
    id: 123,
    variant_id: 57,
    url: "/productos/hoverboards/hoverboards1-3.webp",
    order: 2,
  },
  {
    id: 124,
    variant_id: 58,
    url: "/productos/hoverboards/hoverboards2-1.webp",
    order: 0,
  },
  {
    id: 125,
    variant_id: 58,
    url: "/productos/hoverboards/hoverboards2-2.webp",
    order: 1,
  },
  {
    id: 126,
    variant_id: 58,
    url: "/productos/hoverboards/hoverboards2-3.webp",
    order: 2,
  },
  {
    id: 127,
    variant_id: 59,
    url: "/productos/hoverboards/hoverboards2-1.webp",
    order: 0,
  },
  {
    id: 128,
    variant_id: 59,
    url: "/productos/hoverboards/hoverboards2-2.webp",
    order: 1,
  },
  {
    id: 129,
    variant_id: 59,
    url: "/productos/hoverboards/hoverboards2-3.webp",
    order: 2,
  },
  {
    id: 130,
    variant_id: 60,
    url: "/productos/hoverboards/hoverboards2-1.webp",
    order: 0,
  },
  {
    id: 131,
    variant_id: 60,
    url: "/productos/hoverboards/hoverboards2-2.webp",
    order: 1,
  },
  {
    id: 132,
    variant_id: 60,
    url: "/productos/hoverboards/hoverboards2-3.webp",
    order: 2,
  },
  {
    id: 133,
    variant_id: 61,
    url: "/productos/hoverboards/hoverboards3-1.webp",
    order: 0,
  },
  {
    id: 134,
    variant_id: 61,
    url: "/productos/hoverboards/hoverboards3-2.webp",
    order: 1,
  },
  {
    id: 135,
    variant_id: 61,
    url: "/productos/hoverboards/hoverboards3-3.webp",
    order: 2,
  },
  {
    id: 136,
    variant_id: 62,
    url: "/productos/hoverboards/hoverboards3-1.webp",
    order: 0,
  },
  {
    id: 137,
    variant_id: 62,
    url: "/productos/hoverboards/hoverboards3-2.webp",
    order: 1,
  },
  {
    id: 138,
    variant_id: 62,
    url: "/productos/hoverboards/hoverboards3-3.webp",
    order: 2,
  },
  {
    id: 139,
    variant_id: 63,
    url: "/productos/hoverboards/hoverboards3-1.webp",
    order: 0,
  },
  {
    id: 140,
    variant_id: 63,
    url: "/productos/hoverboards/hoverboards3-2.webp",
    order: 1,
  },
  {
    id: 141,
    variant_id: 63,
    url: "/productos/hoverboards/hoverboards3-3.webp",
    order: 2,
  },
  {
    id: 142,
    variant_id: 64,
    url: "/productos/hoverboards/hoverboards4-1.webp",
    order: 0,
  },
  {
    id: 143,
    variant_id: 64,
    url: "/productos/hoverboards/hoverboards4-2.webp",
    order: 1,
  },
  {
    id: 144,
    variant_id: 64,
    url: "/productos/hoverboards/hoverboards4-3.webp",
    order: 2,
  },
  {
    id: 145,
    variant_id: 65,
    url: "/productos/hoverboards/hoverboards4-1.webp",
    order: 0,
  },
  {
    id: 146,
    variant_id: 65,
    url: "/productos/hoverboards/hoverboards4-2.webp",
    order: 1,
  },
  {
    id: 147,
    variant_id: 65,
    url: "/productos/hoverboards/hoverboards4-3.webp",
    order: 2,
  },
  {
    id: 148,
    variant_id: 66,
    url: "/productos/hoverboards/hoverboards4-1.webp",
    order: 0,
  },
  {
    id: 149,
    variant_id: 66,
    url: "/productos/hoverboards/hoverboards4-2.webp",
    order: 1,
  },
  {
    id: 150,
    variant_id: 66,
    url: "/productos/hoverboards/hoverboards4-3.webp",
    order: 2,
  },
  {
    id: 151,
    variant_id: 67,
    url: "/productos/hoverboards/hoverboards5-1.webp",
    order: 0,
  },
  {
    id: 152,
    variant_id: 67,
    url: "/productos/hoverboards/hoverboards5-2.webp",
    order: 1,
  },
  {
    id: 153,
    variant_id: 67,
    url: "/productos/hoverboards/hoverboards5-3.webp",
    order: 2,
  },
  {
    id: 154,
    variant_id: 68,
    url: "/productos/hoverboards/hoverboards5-1.webp",
    order: 0,
  },
  {
    id: 155,
    variant_id: 68,
    url: "/productos/hoverboards/hoverboards5-2.webp",
    order: 1,
  },
  {
    id: 156,
    variant_id: 68,
    url: "/productos/hoverboards/hoverboards5-3.webp",
    order: 2,
  },
  {
    id: 157,
    variant_id: 69,
    url: "/productos/hoverboards/hoverboards5-1.webp",
    order: 0,
  },
  {
    id: 158,
    variant_id: 69,
    url: "/productos/hoverboards/hoverboards5-2.webp",
    order: 1,
  },
  {
    id: 159,
    variant_id: 69,
    url: "/productos/hoverboards/hoverboards5-3.webp",
    order: 2,
  },
  {
    id: 160,
    variant_id: 70,
    url: "/productos/hoverboards/hoverboards6-1.webp",
    order: 0,
  },
  {
    id: 161,
    variant_id: 70,
    url: "/productos/hoverboards/hoverboards6-2.webp",
    order: 1,
  },
  {
    id: 162,
    variant_id: 70,
    url: "/productos/hoverboards/hoverboards6-3.webp",
    order: 2,
  },
  {
    id: 163,
    variant_id: 71,
    url: "/productos/hoverboards/hoverboards6-1.webp",
    order: 0,
  },
  {
    id: 164,
    variant_id: 71,
    url: "/productos/hoverboards/hoverboards6-2.webp",
    order: 1,
  },
  {
    id: 165,
    variant_id: 71,
    url: "/productos/hoverboards/hoverboards6-3.webp",
    order: 2,
  },
  {
    id: 166,
    variant_id: 72,
    url: "/productos/hoverboards/hoverboards6-1.webp",
    order: 0,
  },
  {
    id: 167,
    variant_id: 72,
    url: "/productos/hoverboards/hoverboards6-2.webp",
    order: 1,
  },
  {
    id: 168,
    variant_id: 72,
    url: "/productos/hoverboards/hoverboards6-3.webp",
    order: 2,
  },
  {
    id: 169,
    variant_id: 73,
    url: "/productos/hoverboards/hoverboards7-1.webp",
    order: 0,
  },
  {
    id: 170,
    variant_id: 73,
    url: "/productos/hoverboards/hoverboards7-2.webp",
    order: 1,
  },
  {
    id: 171,
    variant_id: 73,
    url: "/productos/hoverboards/hoverboards7-3.webp",
    order: 2,
  },
  {
    id: 172,
    variant_id: 74,
    url: "/productos/hoverboards/hoverboards7-1.webp",
    order: 0,
  },
  {
    id: 173,
    variant_id: 74,
    url: "/productos/hoverboards/hoverboards7-2.webp",
    order: 1,
  },
  {
    id: 174,
    variant_id: 74,
    url: "/productos/hoverboards/hoverboards7-3.webp",
    order: 2,
  },
  {
    id: 175,
    variant_id: 75,
    url: "/productos/hoverboards/hoverboards7-1.webp",
    order: 0,
  },
  {
    id: 176,
    variant_id: 75,
    url: "/productos/hoverboards/hoverboards7-2.webp",
    order: 1,
  },
  {
    id: 177,
    variant_id: 75,
    url: "/productos/hoverboards/hoverboards7-3.webp",
    order: 2,
  },
  {
    id: 178,
    variant_id: 76,
    url: "/productos/hoverboards/hoverboards8-1.webp",
    order: 0,
  },
  {
    id: 179,
    variant_id: 76,
    url: "/productos/hoverboards/hoverboards8-2.webp",
    order: 1,
  },
  {
    id: 180,
    variant_id: 76,
    url: "/productos/hoverboards/hoverboards8-3.webp",
    order: 2,
  },
  {
    id: 181,
    variant_id: 77,
    url: "/productos/hoverboards/hoverboards8-1.webp",
    order: 0,
  },
  {
    id: 182,
    variant_id: 77,
    url: "/productos/hoverboards/hoverboards8-2.webp",
    order: 1,
  },
  {
    id: 183,
    variant_id: 77,
    url: "/productos/hoverboards/hoverboards8-3.webp",
    order: 2,
  },
  {
    id: 184,
    variant_id: 78,
    url: "/productos/hoverboards/hoverboards8-1.webp",
    order: 0,
  },
  {
    id: 185,
    variant_id: 78,
    url: "/productos/hoverboards/hoverboards8-2.webp",
    order: 1,
  },
  {
    id: 186,
    variant_id: 78,
    url: "/productos/hoverboards/hoverboards8-3.webp",
    order: 2,
  },
  {
    id: 187,
    variant_id: 79,
    url: "/productos/hoverboards/hoverboards9-1.webp",
    order: 0,
  },
  {
    id: 188,
    variant_id: 79,
    url: "/productos/hoverboards/hoverboards9-2.webp",
    order: 1,
  },
  {
    id: 189,
    variant_id: 79,
    url: "/productos/hoverboards/hoverboards9-3.webp",
    order: 2,
  },
  {
    id: 190,
    variant_id: 80,
    url: "/productos/hoverboards/hoverboards9-1.webp",
    order: 0,
  },
  {
    id: 191,
    variant_id: 80,
    url: "/productos/hoverboards/hoverboards9-2.webp",
    order: 1,
  },
  {
    id: 192,
    variant_id: 80,
    url: "/productos/hoverboards/hoverboards9-3.webp",
    order: 2,
  },
  {
    id: 193,
    variant_id: 81,
    url: "/productos/hoverboards/hoverboards9-1.webp",
    order: 0,
  },
  {
    id: 194,
    variant_id: 81,
    url: "/productos/hoverboards/hoverboards9-2.webp",
    order: 1,
  },
  {
    id: 195,
    variant_id: 81,
    url: "/productos/hoverboards/hoverboards9-3.webp",
    order: 2,
  },
  {
    id: 196,
    variant_id: 82,
    url: "/productos/airfryer/s10-v1-1.webp",
    order: 0,
  },
  {
    id: 197,
    variant_id: 83,
    url: "/productos/airfryer/s10-v1-1.webp",
    order: 0,
  },
  {
    id: 198,
    variant_id: 84,
    url: "/productos/airfryer/s10-v1-1.webp",
    order: 0,
  },
  {
    id: 199,
    variant_id: 85,
    url: "/productos/airfryer/s10-v1-1.webp",
    order: 0,
  },
  {
    id: 200,
    variant_id: 86,
    url: "/productos/airfryer/s10-v1-1.webp",
    order: 0,
  },
  {
    id: 201,
    variant_id: 87,
    url: "/productos/airfryer/s10-v1-1.webp",
    order: 0,
  },
  {
    id: 202,
    variant_id: 88,
    url: "/productos/airfryer/s10-v2-1.webp",
    order: 0,
  },
  {
    id: 203,
    variant_id: 89,
    url: "/productos/airfryer/s10-v2-1.webp",
    order: 0,
  },
  {
    id: 204,
    variant_id: 90,
    url: "/productos/airfryer/s10-v2-1.webp",
    order: 0,
  },
  {
    id: 205,
    variant_id: 91,
    url: "/productos/airfryer/s10-v2-1.webp",
    order: 0,
  },
  {
    id: 206,
    variant_id: 92,
    url: "/productos/airfryer/s10-v2-1.webp",
    order: 0,
  },
  {
    id: 207,
    variant_id: 93,
    url: "/productos/airfryer/s10-v2-1.webp",
    order: 0,
  },
  {
    id: 208,
    variant_id: 94,
    url: "/productos/airfryer/s20-v1-1.webp",
    order: 0,
  },
  {
    id: 209,
    variant_id: 95,
    url: "/productos/airfryer/s20-v1-1.webp",
    order: 0,
  },
  {
    id: 210,
    variant_id: 96,
    url: "/productos/airfryer/s20-v1-1.webp",
    order: 0,
  },
  {
    id: 211,
    variant_id: 97,
    url: "/productos/airfryer/s20-v1-1.webp",
    order: 0,
  },
  {
    id: 212,
    variant_id: 98,
    url: "/productos/airfryer/s20-v1-1.webp",
    order: 0,
  },
  {
    id: 213,
    variant_id: 99,
    url: "/productos/airfryer/s20-v1-1.webp",
    order: 0,
  },
  {
    id: 214,
    variant_id: 100,
    url: "/productos/airfryer/s20-v2-1.webp",
    order: 0,
  },
  {
    id: 215,
    variant_id: 101,
    url: "/productos/airfryer/s20-v2-1.webp",
    order: 0,
  },
  {
    id: 216,
    variant_id: 102,
    url: "/productos/airfryer/s20-v2-1.webp",
    order: 0,
  },
  {
    id: 217,
    variant_id: 103,
    url: "/productos/airfryer/s20-v2-1.webp",
    order: 0,
  },
  {
    id: 218,
    variant_id: 104,
    url: "/productos/airfryer/s20-v2-1.webp",
    order: 0,
  },
  {
    id: 219,
    variant_id: 105,
    url: "/productos/airfryer/s20-v2-1.webp",
    order: 0,
  },
  {
    id: 220,
    variant_id: 106,
    url: "/productos/airfryer/s30-v1-1.webp",
    order: 0,
  },
  {
    id: 221,
    variant_id: 107,
    url: "/productos/airfryer/s30-v1-1.webp",
    order: 0,
  },
  {
    id: 222,
    variant_id: 108,
    url: "/productos/airfryer/s30-v1-1.webp",
    order: 0,
  },
  {
    id: 223,
    variant_id: 109,
    url: "/productos/airfryer/s30-v1-1.webp",
    order: 0,
  },
  {
    id: 224,
    variant_id: 110,
    url: "/productos/airfryer/s30-v1-1.webp",
    order: 0,
  },
  {
    id: 225,
    variant_id: 111,
    url: "/productos/airfryer/s30-v1-1.webp",
    order: 0,
  },
  {
    id: 226,
    variant_id: 112,
    url: "/productos/airfryer/s40-v1-1.webp",
    order: 0,
  },
  {
    id: 227,
    variant_id: 113,
    url: "/productos/airfryer/s40-v1-1.webp",
    order: 0,
  },
  {
    id: 228,
    variant_id: 114,
    url: "/productos/airfryer/s40-v1-1.webp",
    order: 0,
  },
  {
    id: 229,
    variant_id: 115,
    url: "/productos/airfryer/s40-v1-1.webp",
    order: 0,
  },
  {
    id: 230,
    variant_id: 116,
    url: "/productos/airfryer/s40-v1-1.webp",
    order: 0,
  },
  {
    id: 231,
    variant_id: 117,
    url: "/productos/airfryer/s40-v1-1.webp",
    order: 0,
  },
  {
    id: 232,
    variant_id: 118,
    url: "/productos/mixteras/G10-1.webp",
    order: 0,
  },
  {
    id: 233,
    variant_id: 119,
    url: "/productos/mixteras/G10-1.webp",
    order: 0,
  },
  {
    id: 234,
    variant_id: 120,
    url: "/productos/mixteras/G10-1.webp",
    order: 0,
  },
  {
    id: 235,
    variant_id: 121,
    url: "/productos/mixteras/G10-1.webp",
    order: 0,
  },
  {
    id: 236,
    variant_id: 122,
    url: "/productos/mixteras/G10-1.webp",
    order: 0,
  },
  {
    id: 237,
    variant_id: 123,
    url: "/productos/mixteras/G10-1.webp",
    order: 0,
  },
  {
    id: 238,
    variant_id: 124,
    url: "/productos/mixteras/G20-1.webp",
    order: 0,
  },
  {
    id: 239,
    variant_id: 125,
    url: "/productos/mixteras/G20-1.webp",
    order: 0,
  },
  {
    id: 240,
    variant_id: 126,
    url: "/productos/mixteras/G20-1.webp",
    order: 0,
  },
  {
    id: 241,
    variant_id: 127,
    url: "/productos/mixteras/G20-1.webp",
    order: 0,
  },
  {
    id: 242,
    variant_id: 128,
    url: "/productos/mixteras/G20-1.webp",
    order: 0,
  },
  {
    id: 243,
    variant_id: 129,
    url: "/productos/mixteras/G20-1.webp",
    order: 0,
  },
  {
    id: 244,
    variant_id: 130,
    url: "/productos/mixteras/G30-1.webp",
    order: 0,
  },
  {
    id: 245,
    variant_id: 131,
    url: "/productos/mixteras/G30-1.webp",
    order: 0,
  },
  {
    id: 246,
    variant_id: 132,
    url: "/productos/mixteras/G30-1.webp",
    order: 0,
  },
  {
    id: 247,
    variant_id: 133,
    url: "/productos/mixteras/G30-1.webp",
    order: 0,
  },
  {
    id: 248,
    variant_id: 134,
    url: "/productos/mixteras/G30-1.webp",
    order: 0,
  },
  {
    id: 249,
    variant_id: 135,
    url: "/productos/mixteras/G30-1.webp",
    order: 0,
  },
  {
    id: 250,
    variant_id: 136,
    url: "/productos/mixteras/G40-1.webp",
    order: 0,
  },
  {
    id: 251,
    variant_id: 137,
    url: "/productos/mixteras/G40-1.webp",
    order: 0,
  },
  {
    id: 252,
    variant_id: 138,
    url: "/productos/mixteras/G40-1.webp",
    order: 0,
  },
  {
    id: 253,
    variant_id: 139,
    url: "/productos/mixteras/G40-1.webp",
    order: 0,
  },
  {
    id: 254,
    variant_id: 140,
    url: "/productos/mixteras/G40-1.webp",
    order: 0,
  },
  {
    id: 255,
    variant_id: 141,
    url: "/productos/mixteras/G40-1.webp",
    order: 0,
  },
  {
    id: 256,
    variant_id: 142,
    url: "/productos/mixteras/G50-1.webp",
    order: 0,
  },
  {
    id: 257,
    variant_id: 143,
    url: "/productos/mixteras/G50-1.webp",
    order: 0,
  },
  {
    id: 258,
    variant_id: 144,
    url: "/productos/mixteras/G50-1.webp",
    order: 0,
  },
  {
    id: 259,
    variant_id: 145,
    url: "/productos/mixteras/G50-1.webp",
    order: 0,
  },
  {
    id: 260,
    variant_id: 146,
    url: "/productos/mixteras/G50-1.webp",
    order: 0,
  },
  {
    id: 261,
    variant_id: 147,
    url: "/productos/mixteras/G50-1.webp",
    order: 0,
  },
  {
    id: 262,
    variant_id: 148,
    url: "/productos/cocinas/C10-1.webp",
    order: 0,
  },
  {
    id: 263,
    variant_id: 149,
    url: "/productos/cocinas/C10-1.webp",
    order: 0,
  },
  {
    id: 264,
    variant_id: 150,
    url: "/productos/cocinas/C10-1.webp",
    order: 0,
  },
  {
    id: 265,
    variant_id: 151,
    url: "/productos/cocinas/C10-1.webp",
    order: 0,
  },
  {
    id: 266,
    variant_id: 152,
    url: "/productos/cocinas/C10-1.webp",
    order: 0,
  },
  {
    id: 267,
    variant_id: 153,
    url: "/productos/cocinas/C10-1.webp",
    order: 0,
  },
  {
    id: 268,
    variant_id: 154,
    url: "/productos/cocinas/C20-1.webp",
    order: 0,
  },
  {
    id: 269,
    variant_id: 155,
    url: "/productos/cocinas/C20-1.webp",
    order: 0,
  },
  {
    id: 270,
    variant_id: 156,
    url: "/productos/cocinas/C20-1.webp",
    order: 0,
  },
  {
    id: 271,
    variant_id: 157,
    url: "/productos/cocinas/C20-1.webp",
    order: 0,
  },
  {
    id: 272,
    variant_id: 158,
    url: "/productos/cocinas/C20-1.webp",
    order: 0,
  },
  {
    id: 273,
    variant_id: 159,
    url: "/productos/cocinas/C20-1.webp",
    order: 0,
  },
  {
    id: 274,
    variant_id: 160,
    url: "/productos/cocinas/C30-1.webp",
    order: 0,
  },
  {
    id: 275,
    variant_id: 161,
    url: "/productos/cocinas/C30-1.webp",
    order: 0,
  },
  {
    id: 276,
    variant_id: 162,
    url: "/productos/cocinas/C30-1.webp",
    order: 0,
  },
  {
    id: 277,
    variant_id: 163,
    url: "/productos/cocinas/C30-1.webp",
    order: 0,
  },
  {
    id: 278,
    variant_id: 164,
    url: "/productos/cocinas/C30-1.webp",
    order: 0,
  },
  {
    id: 279,
    variant_id: 165,
    url: "/productos/cocinas/C30-1.webp",
    order: 0,
  },
  {
    id: 280,
    variant_id: 166,
    url: "/productos/hervidoras/T10-1.webp",
    order: 0,
  },
  {
    id: 281,
    variant_id: 167,
    url: "/productos/hervidoras/T10-1.webp",
    order: 0,
  },
  {
    id: 282,
    variant_id: 168,
    url: "/productos/hervidoras/T10-1.webp",
    order: 0,
  },
  {
    id: 283,
    variant_id: 169,
    url: "/productos/hervidoras/T10-1.webp",
    order: 0,
  },
  {
    id: 284,
    variant_id: 170,
    url: "/productos/hervidoras/T10-1.webp",
    order: 0,
  },
  {
    id: 285,
    variant_id: 171,
    url: "/productos/hervidoras/T10-1.webp",
    order: 0,
  },
  {
    id: 286,
    variant_id: 172,
    url: "/productos/hervidoras/T20-1.webp",
    order: 0,
  },
  {
    id: 287,
    variant_id: 173,
    url: "/productos/hervidoras/T20-1.webp",
    order: 0,
  },
  {
    id: 288,
    variant_id: 174,
    url: "/productos/hervidoras/T20-1.webp",
    order: 0,
  },
  {
    id: 289,
    variant_id: 175,
    url: "/productos/hervidoras/T20-1.webp",
    order: 0,
  },
  {
    id: 290,
    variant_id: 176,
    url: "/productos/hervidoras/T20-1.webp",
    order: 0,
  },
  {
    id: 291,
    variant_id: 177,
    url: "/productos/hervidoras/T20-1.webp",
    order: 0,
  },
  {
    id: 292,
    variant_id: 178,
    url: "/productos/hervidoras/T30-1.webp",
    order: 0,
  },
  {
    id: 293,
    variant_id: 179,
    url: "/productos/hervidoras/T30-1.webp",
    order: 0,
  },
  {
    id: 294,
    variant_id: 180,
    url: "/productos/hervidoras/T30-1.webp",
    order: 0,
  },
  {
    id: 295,
    variant_id: 181,
    url: "/productos/hervidoras/T30-1.webp",
    order: 0,
  },
  {
    id: 296,
    variant_id: 182,
    url: "/productos/hervidoras/T30-1.webp",
    order: 0,
  },
  {
    id: 297,
    variant_id: 183,
    url: "/productos/hervidoras/T30-1.webp",
    order: 0,
  },
  {
    id: 298,
    variant_id: 184,
    url: "/productos/cafeteras/E10-1.webp",
    order: 0,
  },
  {
    id: 299,
    variant_id: 185,
    url: "/productos/cafeteras/E10-1.webp",
    order: 0,
  },
  {
    id: 300,
    variant_id: 186,
    url: "/productos/cafeteras/E10-1.webp",
    order: 0,
  },
  {
    id: 301,
    variant_id: 187,
    url: "/productos/cafeteras/E10-1.webp",
    order: 0,
  },
  {
    id: 302,
    variant_id: 188,
    url: "/productos/cafeteras/E10-1.webp",
    order: 0,
  },
  {
    id: 303,
    variant_id: 189,
    url: "/productos/cafeteras/E10-1.webp",
    order: 0,
  },
  {
    id: 304,
    variant_id: 190,
    url: "/productos/planchas/F10-1.webp",
    order: 0,
  },
  {
    id: 305,
    variant_id: 191,
    url: "/productos/planchas/F10-1.webp",
    order: 0,
  },
  {
    id: 306,
    variant_id: 192,
    url: "/productos/planchas/F10-1.webp",
    order: 0,
  },
  {
    id: 307,
    variant_id: 193,
    url: "/productos/planchas/F10-1.webp",
    order: 0,
  },
  {
    id: 308,
    variant_id: 194,
    url: "/productos/planchas/F10-1.webp",
    order: 0,
  },
  {
    id: 309,
    variant_id: 195,
    url: "/productos/planchas/F10-1.webp",
    order: 0,
  },
  {
    id: 310,
    variant_id: 196,
    url: "/productos/planchas/F20-1.webp",
    order: 0,
  },
  {
    id: 311,
    variant_id: 197,
    url: "/productos/planchas/F20-1.webp",
    order: 0,
  },
  {
    id: 312,
    variant_id: 198,
    url: "/productos/planchas/F20-1.webp",
    order: 0,
  },
  {
    id: 313,
    variant_id: 199,
    url: "/productos/planchas/F20-1.webp",
    order: 0,
  },
  {
    id: 314,
    variant_id: 200,
    url: "/productos/planchas/F20-1.webp",
    order: 0,
  },
  {
    id: 315,
    variant_id: 201,
    url: "/productos/planchas/F20-1.webp",
    order: 0,
  },
  {
    id: 316,
    variant_id: 202,
    url: "/productos/planchas/F30-1.webp",
    order: 0,
  },
  {
    id: 317,
    variant_id: 203,
    url: "/productos/planchas/F30-1.webp",
    order: 0,
  },
  {
    id: 318,
    variant_id: 204,
    url: "/productos/planchas/F30-1.webp",
    order: 0,
  },
  {
    id: 319,
    variant_id: 205,
    url: "/productos/planchas/F40-1.webp",
    order: 0,
  },
  {
    id: 320,
    variant_id: 206,
    url: "/productos/planchas/F40-1.webp",
    order: 0,
  },
  {
    id: 321,
    variant_id: 207,
    url: "/productos/planchas/F40-1.webp",
    order: 0,
  },
  {
    id: 322,
    variant_id: 208,
    url: "/productos/planchas/F40-1.webp",
    order: 0,
  },
  {
    id: 323,
    variant_id: 209,
    url: "/productos/planchas/F40-1.webp",
    order: 0,
  },
  {
    id: 324,
    variant_id: 210,
    url: "/productos/planchas/F40-1.webp",
    order: 0,
  },
  {
    id: 325,
    variant_id: 211,
    url: "/productos/planchas/F50-1.webp",
    order: 0,
  },
  {
    id: 326,
    variant_id: 212,
    url: "/productos/planchas/F50-1.webp",
    order: 0,
  },
  {
    id: 327,
    variant_id: 213,
    url: "/productos/planchas/F50-1.webp",
    order: 0,
  },
  {
    id: 328,
    variant_id: 214,
    url: "/productos/planchas/F50-1.webp",
    order: 0,
  },
  {
    id: 329,
    variant_id: 215,
    url: "/productos/planchas/F50-1.webp",
    order: 0,
  },
  {
    id: 330,
    variant_id: 216,
    url: "/productos/planchas/F50-1.webp",
    order: 0,
  },
  {
    id: 331,
    variant_id: 217,
    url: "/productos/licuadoras/L10-1.webp",
    order: 0,
  },
  {
    id: 332,
    variant_id: 218,
    url: "/productos/licuadoras/L10-1.webp",
    order: 0,
  },
  {
    id: 333,
    variant_id: 219,
    url: "/productos/licuadoras/L10-1.webp",
    order: 0,
  },
  {
    id: 334,
    variant_id: 220,
    url: "/productos/licuadoras/L10-1.webp",
    order: 0,
  },
  {
    id: 335,
    variant_id: 221,
    url: "/productos/licuadoras/L10-1.webp",
    order: 0,
  },
  {
    id: 336,
    variant_id: 222,
    url: "/productos/licuadoras/L10-1.webp",
    order: 0,
  },
  {
    id: 337,
    variant_id: 223,
    url: "/productos/licuadoras/L20-1.webp",
    order: 0,
  },
  {
    id: 338,
    variant_id: 223,
    url: "/productos/licuadoras/L20-2.webp",
    order: 1,
  },
  {
    id: 339,
    variant_id: 223,
    url: "/productos/licuadoras/L20-3.webp",
    order: 2,
  },
  {
    id: 340,
    variant_id: 224,
    url: "/productos/licuadoras/L20-1.webp",
    order: 0,
  },
  {
    id: 341,
    variant_id: 224,
    url: "/productos/licuadoras/L20-2.webp",
    order: 1,
  },
  {
    id: 342,
    variant_id: 224,
    url: "/productos/licuadoras/L20-3.webp",
    order: 2,
  },
  {
    id: 343,
    variant_id: 225,
    url: "/productos/licuadoras/L20-1.webp",
    order: 0,
  },
  {
    id: 344,
    variant_id: 225,
    url: "/productos/licuadoras/L20-2.webp",
    order: 1,
  },
  {
    id: 345,
    variant_id: 225,
    url: "/productos/licuadoras/L20-3.webp",
    order: 2,
  },
  {
    id: 346,
    variant_id: 226,
    url: "/productos/licuadoras/L20-1.webp",
    order: 0,
  },
  {
    id: 347,
    variant_id: 226,
    url: "/productos/licuadoras/L20-2.webp",
    order: 1,
  },
  {
    id: 348,
    variant_id: 226,
    url: "/productos/licuadoras/L20-3.webp",
    order: 2,
  },
  {
    id: 349,
    variant_id: 227,
    url: "/productos/licuadoras/L20-1.webp",
    order: 0,
  },
  {
    id: 350,
    variant_id: 227,
    url: "/productos/licuadoras/L20-2.webp",
    order: 1,
  },
  {
    id: 351,
    variant_id: 227,
    url: "/productos/licuadoras/L20-3.webp",
    order: 2,
  },
  {
    id: 352,
    variant_id: 228,
    url: "/productos/licuadoras/L20-1.webp",
    order: 0,
  },
  {
    id: 353,
    variant_id: 228,
    url: "/productos/licuadoras/L20-2.webp",
    order: 1,
  },
  {
    id: 354,
    variant_id: 228,
    url: "/productos/licuadoras/L20-3.webp",
    order: 2,
  },
  {
    id: 355,
    variant_id: 229,
    url: "/productos/licuadoras/L30-1.webp",
    order: 0,
  },
  {
    id: 356,
    variant_id: 230,
    url: "/productos/licuadoras/L30-1.webp",
    order: 0,
  },
  {
    id: 357,
    variant_id: 231,
    url: "/productos/licuadoras/L30-1.webp",
    order: 0,
  },
  {
    id: 358,
    variant_id: 232,
    url: "/productos/licuadoras/L30-1.webp",
    order: 0,
  },
  {
    id: 359,
    variant_id: 233,
    url: "/productos/licuadoras/L30-1.webp",
    order: 0,
  },
  {
    id: 360,
    variant_id: 234,
    url: "/productos/licuadoras/L30-1.webp",
    order: 0,
  },
  {
    id: 361,
    variant_id: 235,
    url: "/productos/licuadoras/L40-1.webp",
    order: 0,
  },
  {
    id: 362,
    variant_id: 235,
    url: "/productos/licuadoras/L40-2.webp",
    order: 1,
  },
  {
    id: 363,
    variant_id: 235,
    url: "/productos/licuadoras/L40-3.webp",
    order: 2,
  },
  {
    id: 364,
    variant_id: 236,
    url: "/productos/licuadoras/L40-1.webp",
    order: 0,
  },
  {
    id: 365,
    variant_id: 236,
    url: "/productos/licuadoras/L40-2.webp",
    order: 1,
  },
  {
    id: 366,
    variant_id: 236,
    url: "/productos/licuadoras/L40-3.webp",
    order: 2,
  },
  {
    id: 367,
    variant_id: 237,
    url: "/productos/licuadoras/L40-1.webp",
    order: 0,
  },
  {
    id: 368,
    variant_id: 237,
    url: "/productos/licuadoras/L40-2.webp",
    order: 1,
  },
  {
    id: 369,
    variant_id: 237,
    url: "/productos/licuadoras/L40-3.webp",
    order: 2,
  },
  {
    id: 370,
    variant_id: 238,
    url: "/productos/licuadoras/L40-1.webp",
    order: 0,
  },
  {
    id: 371,
    variant_id: 238,
    url: "/productos/licuadoras/L40-2.webp",
    order: 1,
  },
  {
    id: 372,
    variant_id: 238,
    url: "/productos/licuadoras/L40-3.webp",
    order: 2,
  },
  {
    id: 373,
    variant_id: 239,
    url: "/productos/licuadoras/L40-1.webp",
    order: 0,
  },
  {
    id: 374,
    variant_id: 239,
    url: "/productos/licuadoras/L40-2.webp",
    order: 1,
  },
  {
    id: 375,
    variant_id: 239,
    url: "/productos/licuadoras/L40-3.webp",
    order: 2,
  },
  {
    id: 376,
    variant_id: 240,
    url: "/productos/licuadoras/L40-1.webp",
    order: 0,
  },
  {
    id: 377,
    variant_id: 240,
    url: "/productos/licuadoras/L40-2.webp",
    order: 1,
  },
  {
    id: 378,
    variant_id: 240,
    url: "/productos/licuadoras/L40-3.webp",
    order: 2,
  },
  {
    id: 379,
    variant_id: 241,
    url: "/productos/beauty/603D-1.webp",
    order: 0,
  },
  {
    id: 380,
    variant_id: 242,
    url: "/productos/beauty/603D-1.webp",
    order: 0,
  },
  {
    id: 381,
    variant_id: 243,
    url: "/productos/beauty/603D-1.webp",
    order: 0,
  },
  {
    id: 382,
    variant_id: 244,
    url: "/productos/beauty/HB40-1.webp",
    order: 0,
  },
  {
    id: 383,
    variant_id: 245,
    url: "/productos/beauty/HB40-1.webp",
    order: 0,
  },
  {
    id: 384,
    variant_id: 246,
    url: "/productos/beauty/HB40-1.webp",
    order: 0,
  },
  {
    id: 385,
    variant_id: 247,
    url: "/productos/beauty/HD008-1.webp",
    order: 0,
  },
  {
    id: 386,
    variant_id: 248,
    url: "/productos/beauty/HD008-1.webp",
    order: 0,
  },
  {
    id: 387,
    variant_id: 249,
    url: "/productos/beauty/HD008-1.webp",
    order: 0,
  },
  {
    id: 388,
    variant_id: 250,
    url: "/productos/beauty/RFCD865-1.webp",
    order: 0,
  },
  {
    id: 389,
    variant_id: 251,
    url: "/productos/beauty/RFCD865-1.webp",
    order: 0,
  },
  {
    id: 390,
    variant_id: 252,
    url: "/productos/beauty/RFCD865-1.webp",
    order: 0,
  },
  {
    id: 391,
    variant_id: 253,
    url: "/productos/batidoras/B10-1.webp",
    order: 0,
  },
  {
    id: 392,
    variant_id: 254,
    url: "/productos/batidoras/B10-1.webp",
    order: 0,
  },
  {
    id: 393,
    variant_id: 255,
    url: "/productos/batidoras/B10-1.webp",
    order: 0,
  },
  {
    id: 394,
    variant_id: 256,
    url: "/productos/batidoras/B10-1.webp",
    order: 0,
  },
  {
    id: 395,
    variant_id: 257,
    url: "/productos/batidoras/B10-1.webp",
    order: 0,
  },
  {
    id: 396,
    variant_id: 258,
    url: "/productos/batidoras/B10-1.webp",
    order: 0,
  },
  {
    id: 397,
    variant_id: 259,
    url: "/productos/batidoras/B20-1.webp",
    order: 0,
  },
  {
    id: 398,
    variant_id: 260,
    url: "/productos/batidoras/B20-1.webp",
    order: 0,
  },
  {
    id: 399,
    variant_id: 261,
    url: "/productos/batidoras/B20-1.webp",
    order: 0,
  },
  {
    id: 400,
    variant_id: 262,
    url: "/productos/batidoras/B20-1.webp",
    order: 0,
  },
  {
    id: 401,
    variant_id: 263,
    url: "/productos/batidoras/B20-1.webp",
    order: 0,
  },
  {
    id: 402,
    variant_id: 264,
    url: "/productos/batidoras/B20-1.webp",
    order: 0,
  },
  {
    id: 403,
    variant_id: 265,
    url: "/productos/batidoras/B30-1.webp",
    order: 0,
  },
  {
    id: 404,
    variant_id: 266,
    url: "/productos/batidoras/B30-1.webp",
    order: 0,
  },
  {
    id: 405,
    variant_id: 267,
    url: "/productos/batidoras/B30-1.webp",
    order: 0,
  },
  {
    id: 406,
    variant_id: 268,
    url: "/productos/batidoras/B30-1.webp",
    order: 0,
  },
  {
    id: 407,
    variant_id: 269,
    url: "/productos/batidoras/B30-1.webp",
    order: 0,
  },
  {
    id: 408,
    variant_id: 270,
    url: "/productos/batidoras/B30-1.webp",
    order: 0,
  },
  {
    id: 409,
    variant_id: 271,
    url: "/productos/arroceras/A10-1.webp",
    order: 0,
  },
  {
    id: 410,
    variant_id: 272,
    url: "/productos/arroceras/A10-1.webp",
    order: 0,
  },
  {
    id: 411,
    variant_id: 273,
    url: "/productos/arroceras/A10-1.webp",
    order: 0,
  },
  {
    id: 412,
    variant_id: 274,
    url: "/productos/arroceras/A10-1.webp",
    order: 0,
  },
  {
    id: 413,
    variant_id: 275,
    url: "/productos/arroceras/A10-1.webp",
    order: 0,
  },
  {
    id: 414,
    variant_id: 276,
    url: "/productos/arroceras/A10-1.webp",
    order: 0,
  },
  {
    id: 415,
    variant_id: 277,
    url: "/productos/arroceras/P10-1.webp",
    order: 0,
  },
  {
    id: 416,
    variant_id: 278,
    url: "/productos/arroceras/P10-1.webp",
    order: 0,
  },
  {
    id: 417,
    variant_id: 279,
    url: "/productos/arroceras/P10-1.webp",
    order: 0,
  },
  {
    id: 418,
    variant_id: 280,
    url: "/productos/arroceras/P10-1.webp",
    order: 0,
  },
  {
    id: 419,
    variant_id: 281,
    url: "/productos/arroceras/P10-1.webp",
    order: 0,
  },
  {
    id: 420,
    variant_id: 282,
    url: "/productos/arroceras/P10-1.webp",
    order: 0,
  },
  {
    id: 421,
    variant_id: 283,
    url: "/productos/bebederos/W10-1.webp",
    order: 0,
  },
  {
    id: 422,
    variant_id: 284,
    url: "/productos/bebederos/W10-1.webp",
    order: 0,
  },
  {
    id: 423,
    variant_id: 285,
    url: "/productos/bebederos/W10-1.webp",
    order: 0,
  },
  {
    id: 424,
    variant_id: 286,
    url: "/productos/bebederos/W10-1.webp",
    order: 0,
  },
  {
    id: 425,
    variant_id: 287,
    url: "/productos/bebederos/W10-1.webp",
    order: 0,
  },
  {
    id: 426,
    variant_id: 288,
    url: "/productos/bebederos/W10-1.webp",
    order: 0,
  },
];

const ALL_VOLTAJES = [
  { id: 1, name: "120V" },
  { id: 2, name: "220V" },
  { id: 3, name: "Bivolt" },
];

const init = async () => {
  
  if (import.meta.env.PROD) return;

  // truncate tables
  await db.delete(Photo).execute();
  await db.delete(Color).execute();
  await db.delete(Volt).execute();
  await db.delete(Variant).execute();
  await db.delete(Product).execute();
  await db.delete(Category).execute();

  const categories = await db.insert(Category).values(ALL_CATEGORIES);
  const volts = await db.insert(Volt).values(ALL_VOLTAJES);
  const colors = await db.insert(Color).values(ALL_COLORS);
  const products = await db.insert(Product).values(ALL_PRODUCTS);
  const variants = await db.insert(Variant).values(ALL_VARIANTS);
  const photos = await db.insert(Photo).values(ALL_PHOTOS);

  return { categories, volts, colors, products, variants, photos };
}

export function seedDatabase() {

  init().then(() => {
    console.log("Database seeded successfully");
  }).catch(() => {
    console.error("Error seeding database");
  });
  

}